#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

"""frequency_response.plotTool.cli

Import shim so you can run both:
  - python -m frequency_response.plotTool.cli
  - python cli.py (from inside frequency_response/plotTool)

Also includes a small Sphinx helper:
  - python -m frequency_response.plotTool.cli sphinx-skel frequency_response/plotTool/docs
"""

import argparse
import os
import sys
import warnings
import platform
import traceback
from pathlib import Path
from typing import Optional

# Import shim
if __package__ in (None, ""):
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from frequency_response.plotTool.app import PlotToolApp  # type: ignore
    from frequency_response.plotTool.apis import PlotService, PlotRequest  # type: ignore
    from frequency_response.plotTool.utils import build_logger, parse_csv_vals, parse_range4  # type: ignore
else:
    from .app import PlotToolApp
    from .apis import PlotService, PlotRequest
    from .utils import build_logger, parse_csv_vals, parse_range4


# -------------------------- Sphinx skeleton helper --------------------------

def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    """
    Create a minimal Sphinx docs skeleton under ``dest``.

    Files written:
      - conf.py    Adds repo root to sys.path for autodoc and sets project metadata.
      - index.rst  Main docs landing page.
      - api.rst    Autodoc page for plotTool modules.
      - Makefile   Convenience targets: make html / make clean.

    Existing files are preserved unless ``force=True``.
    """
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)

    conf = (
        "# Generated by frequency_response.plotTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> plotTool -> frequency_response -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n"
        "\n"
        "project = 'modernControl - frequency_response.plotTool'\n"
        "author = 'modernControl'\n"
        "\n"
        "extensions = [\n"
        "    'sphinx.ext.autodoc',\n"
        "    'sphinx.ext.napoleon',\n"
        "    'sphinx.ext.viewcode',\n"
        "]\n"
        "\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']\n"
        "html_theme = 'furo'\n"
        "html_static_path = ['_static']\n"
        "autodoc_typehints = 'description'\n"
    )

    index = (
        ".. frequency_response.plotTool documentation master file\n\n"
        "frequency_response.plotTool\n"
        "===========================\n\n"
        "A plotting-focused frequency-response toolkit for Bode, Nyquist, and Nichols workflows.\n\n"
        ".. toctree::\n"
        "   :maxdepth: 2\n"
        "   :caption: Contents:\n\n"
        "   api\n"
    )

    api = (
        "API Reference\n"
        "=============\n\n"
        "Application Layer\n"
        "-----------------\n\n"
        ".. automodule:: frequency_response.plotTool.app\n"
        "   :members:\n"
        "   :undoc-members:\n"
        "   :show-inheritance:\n\n"
        "Service/API Layer\n"
        "-----------------\n\n"
        ".. automodule:: frequency_response.plotTool.apis\n"
        "   :members:\n"
        "   :undoc-members:\n"
        "   :show-inheritance:\n\n"
        "Core Logic\n"
        "----------\n\n"
        ".. automodule:: frequency_response.plotTool.core\n"
        "   :members:\n"
        "   :undoc-members:\n"
        "   :show-inheritance:\n\n"
        "Input/Output\n"
        "------------\n\n"
        ".. automodule:: frequency_response.plotTool.io\n"
        "   :members:\n"
        "   :undoc-members:\n"
        "   :show-inheritance:\n\n"
        "Utilities\n"
        "---------\n\n"
        ".. automodule:: frequency_response.plotTool.utils\n"
        "   :members:\n"
        "   :undoc-members:\n"
        "   :show-inheritance:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile generated by frequency_response.plotTool.cli\n"
        ".PHONY: html clean\n"
        "html:\n"
        "\t+sphinx-build -b html . _build/html\n"
        "clean:\n"
        "\t+rm -rf _build\n"
    )

    def _write(path: Path, text: str) -> None:
        if path.exists() and not force:
            return
        path.write_text(text, encoding="utf-8")

    (dest / "_templates").mkdir(exist_ok=True)
    (dest / "_static").mkdir(exist_ok=True)
    _write(dest / "conf.py", conf)
    _write(dest / "index.rst", index)
    _write(dest / "api.rst", api)
    _write(dest / "Makefile", makefile)
    return dest


def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="sphinx-skel",
        description="Create a minimal Sphinx docs skeleton for frequency_response.plotTool.",
    )
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    ap.add_argument("--force", action="store_true", help="Overwrite existing files if present")
    return ap


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Frequency-response plotTool (Bode, Nyquist, Nichols) - modernControl")
    ap.add_argument("--num")
    ap.add_argument("--den")
    ap.add_argument("--gain", type=float)
    ap.add_argument("--zeros")
    ap.add_argument("--poles")
    ap.add_argument("--fnum")
    ap.add_argument("--fden")
    ap.add_argument("--K", type=float, default=1.0)
    ap.add_argument("--A")
    ap.add_argument("--B")
    ap.add_argument("--C")
    ap.add_argument("--D")
    ap.add_argument("--scale", type=float)
    ap.add_argument("--wmin", type=float)
    ap.add_argument("--wmax", type=float)
    ap.add_argument("--npts", type=int, default=400)
    ap.add_argument("--bode", action="store_true")
    ap.add_argument("--nyquist", action="store_true")
    ap.add_argument("--nichols", action="store_true")
    ap.add_argument("--nichols-grid", action="store_true")
    ap.add_argument("--nichols-closedloop", action="store_true")
    ap.add_argument("--nyq-markers", action="store_true")
    ap.add_argument("--nyq-samples", type=int, default=0)
    ap.add_argument("--plotly", action="store_true")
    ap.add_argument("--wmarks")
    ap.add_argument("--nichols-range")
    ap.add_argument("--nichols-Mdb", nargs="*", type=float)
    ap.add_argument("--nichols-Mdb-csv", type=str)
    ap.add_argument("--nichols-Ndeg", nargs="*", type=float)
    ap.add_argument("--nichols-Ndeg-csv", type=str)
    ap.add_argument("--nichols-no-grid-labels", action="store_true")
    ap.add_argument("--save-png", help="Folder for PNG files (Matplotlib).")
    ap.add_argument("--save-html", help="Base name for Plotly HTML (suffixes added).")
    ap.add_argument("--save-json", help="Write a JSON report.")
    ap.add_argument("--title", default="Frequency Response")
    ap.add_argument("-v", "--verbose", action="count", default=0)
    return ap


def _debug_banner(args: argparse.Namespace) -> None:
    try:
        import numpy  # type: ignore
        import control  # type: ignore
        import matplotlib  # type: ignore
        import plotly  # type: ignore
    except Exception:
        numpy = control = matplotlib = plotly = None  # type: ignore

    print("\n[plotTool DEBUG] Python:", sys.version)
    print("[plotTool DEBUG] Platform:", platform.platform())
    print("[plotTool DEBUG] CWD:", os.getcwd())
    print("[plotTool DEBUG] argv:", sys.argv)
    print("[plotTool DEBUG] parsed args:", args)
    if numpy:
        print("[plotTool DEBUG] numpy:", numpy.__version__)
    if control:
        print("[plotTool DEBUG] python-control:", getattr(control, "__version__", "?"))
    if matplotlib:
        try:
            import matplotlib as _mpl  # type: ignore
            print("[plotTool DEBUG] matplotlib:", _mpl.__version__)
            print("[plotTool DEBUG] MPL backend:", _mpl.get_backend())
        except Exception:
            pass
    if plotly:
        print("[plotTool DEBUG] plotly:", plotly.__version__)


def _parse_wmarks(raw: Optional[str]) -> Optional[list[float]]:
    if not raw:
        return None
    return [float(x) for x in raw.replace(";", ",").split(",") if x.strip()]


def main(argv: Optional[list[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    # Non-invasive docs helper. This exits before normal argparse parsing so it
    # cannot interfere with existing plotTool run flags.
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return 0

    ap = build_parser()
    args = ap.parse_args(argv)

    debug = bool(os.environ.get("PLOTTOOL_DEBUG", ""))
    if debug:
        _debug_banner(args)

    _ = build_logger("plotTool", level=(10 if args.verbose and args.verbose >= 1 else 20))

    req = PlotRequest(
        bode=args.bode,
        nyquist=args.nyquist,
        nichols=args.nichols,
        nichols_grid=args.nichols_grid,
        nichols_closedloop=args.nichols_closedloop,
        plotly=args.plotly,
        nyq_markers=args.nyq_markers,
        nyq_samples=args.nyq_samples,
        wmin=args.wmin,
        wmax=args.wmax,
        npts=args.npts,
        wmarks=_parse_wmarks(args.wmarks),
        nichols_range=parse_range4(args.nichols_range),
        nichols_Mdb=(
            args.nichols_Mdb
            if (args.nichols_Mdb and len(args.nichols_Mdb) > 0)
            else parse_csv_vals(args.nichols_Mdb_csv)
        ),
        nichols_Ndeg=(
            args.nichols_Ndeg
            if (args.nichols_Ndeg and len(args.nichols_Ndeg) > 0)
            else parse_csv_vals(args.nichols_Ndeg_csv)
        ),
        nichols_no_grid_labels=args.nichols_no_grid_labels,
        save_png_dir=args.save_png,
        save_html_base=args.save_html,
        save_json_path=args.save_json,
        title=args.title,
    )

    app = PlotToolApp()
    svc = PlotService(app)
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=FutureWarning)
            svc.run(args, req)
    except Exception:
        if debug:
            print("[plotTool DEBUG] Exception raised:")
            traceback.print_exc()
        raise

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
