"""Command line interface for the state-space MIMO analysis tool."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import click
import matplotlib

matplotlib.use("Agg")  # headless by default for scripts/tests

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_analysis/mimoTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_analysis.mimoTool.app import MIMOToolApp
else:
    from .app import MIMOToolApp


_PACKAGE = "state_space_analysis.mimoTool"
_PROJECT = "modernControl - state_space_analysis.mimoTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_analysis.mimoTool.cli",
    "state_space_analysis.mimoTool.apis",
    "state_space_analysis.mimoTool.app",
    "state_space_analysis.mimoTool.core",
    "state_space_analysis.mimoTool.design",
    "state_space_analysis.mimoTool.io",
    "state_space_analysis.mimoTool.utils",
]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> mimoTool -> state_space_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the project-standard minimal Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


@click.group(help="MIMO analysis tool for state-space models.")
def cli() -> None:
    """Command line interface for MIMO analysis."""
    pass


@cli.command("describe", help="Describe a built-in MIMO plant model.")
@click.option("--plant", type=click.Choice(["two_tank", "two_zone_thermal"]), required=True)
def cmd_describe(plant: str) -> None:
    """Print a JSON description of a built-in plant model."""
    app = MIMOToolApp()
    info = app.run_describe(plant)
    click.echo(json.dumps(info, indent=2, default=str))


@cli.command("steps", help="Generate MIMO step responses for a built-in plant model.")
@click.option("--plant", type=click.Choice(["two_tank", "two_zone_thermal"]), required=True)
@click.option("--tfinal", type=float, default=100.0, show_default=True)
@click.option("--dt", type=float, default=0.1, show_default=True)
@click.option("--save/--no-save", default=False, show_default=True)
@click.option("--out-prefix", type=str, default=None)
def cmd_steps(plant: str, tfinal: float, dt: float, save: bool, out_prefix: str | None) -> None:
    """Run step-response analysis and optionally save output files."""
    app = MIMOToolApp()
    paths = app.run_steps(plant, tfinal=tfinal, dt=dt, save=save, out_prefix=out_prefix)
    if save:
        for path in paths:
            click.echo(path)


@cli.command("sigma", help="Generate singular-value analysis for a built-in plant model.")
@click.option("--plant", type=click.Choice(["two_tank", "two_zone_thermal"]), required=True)
@click.option("--save/--no-save", default=False, show_default=True)
@click.option("--out-name", type=str, default=None)
def cmd_sigma(plant: str, save: bool, out_name: str | None) -> None:
    """Run singular-value analysis and optionally save an output file."""
    app = MIMOToolApp()
    path = app.run_sigma(plant, save=save, out_name=out_name)
    if save and path:
        click.echo(path)


@cli.command("sphinx-skel", help="Create a deploy-safe Sphinx documentation skeleton for this package.")
@click.argument("dest", type=click.Path(file_okay=False, dir_okay=True, path_type=Path))
@click.option("--force", is_flag=True, help="Overwrite existing Sphinx skeleton files.")
def sphinx_skel(dest: Path, force: bool) -> None:
    """Generate Sphinx files with safe headings and tracked support folders."""
    written = _write_sphinx_skeleton(dest, force=force)
    click.echo(f"Sphinx skeleton ready: {dest}")
    if written:
        click.echo("Written files:")
        for path in written:
            click.echo(f"  {path}")
    else:
        click.echo("No existing files were overwritten. Use --force to regenerate.")
    click.echo("Support files ensured:")
    click.echo(f"  {dest / '_static' / '.gitkeep'}")
    click.echo(f"  {dest / '_templates' / '.gitkeep'}")


def main() -> None:
    """Run the MIMO tool command line interface."""
    cli()


if __name__ == "__main__":
    main()
