
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from within the package folder.
    # Add project root to sys.path (../../)
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    # Import absolute modules
    from modeling_control_systems.canonicalTool.apis import RunRequest
    from modeling_control_systems.canonicalTool.app import CanonicalApp
    from modeling_control_systems.canonicalTool.io import parse_coeffs
else:
    # Normal package execution (e.g., `python -m modeling_control_systems.canonicalTool.cli`)
    from .apis import RunRequest
    from .app import CanonicalApp
    from .io import parse_coeffs

def _level(v: int):
    return logging.DEBUG if v >= 2 else (logging.INFO if v == 1 else logging.INFO)

# -------------------------- Sphinx skeleton helper --------------------------

def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    """Create a minimal Sphinx docs skeleton under ``dest`` for canonicalTool."""
    dest.mkdir(parents=True, exist_ok=True)

    conf = (
        "# Generated by modeling_control_systems.canonicalTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> canonicalTool -> modeling_control_systems -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n"
        "project = 'modernControl – modeling_control_systems.canonicalTool'\n"
        "extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = []\n"
        "html_theme = 'furo'\n"
    )

    index = (
        ".. modeling_control_systems.canonicalTool documentation master file\n\n"
        "Welcome to modeling_control_systems.canonicalTool's docs!\n"
        "===============================================\n\n"
        ".. toctree::\n"
        "   :maxdepth: 2\n"
        "   :caption: Contents:\n\n"
        "   api\n"
    )

    api = (
        "API Reference\n"
        "=============\n\n"
        ".. automodule:: modeling_control_systems.canonicalTool.app\n"
        "   :members:\n"
        "   :undoc-members:\n\n"
        ".. automodule:: modeling_control_systems.canonicalTool.apis\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: modeling_control_systems.canonicalTool.core\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: modeling_control_systems.canonicalTool.io\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: modeling_control_systems.canonicalTool.utils\n"
        "   :members:\n"
        "   :undoc-members:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    def _write(path: Path, text: str):
        if path.exists() and not force:
            return
        path.write_text(text, encoding="utf-8")

    (dest / "_templates").mkdir(exist_ok=True)
    (dest / "_static").mkdir(exist_ok=True)
    _write(dest / "conf.py", conf)
    _write(dest / "index.rst", index)
    _write(dest / "api.rst", api)
    _write(dest / "Makefile", makefile)
    return dest

# ------------------------------ CLI parsers --------------------------------

def _build_run_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="SISO canonical forms demo (CCF / OCF / Modal-real)")
    ap.add_argument("--num", required=True, help="numerator coeffs, e.g., '2,3'")
    ap.add_argument("--den", required=True, help="denominator coeffs, e.g., '1,1,10'")
    ap.add_argument("--tfinal", type=float, default=8.0)
    ap.add_argument("--dt", type=float, default=1e-3)
    ap.add_argument("--symbolic", action="store_true", help="print symbolic G(s) if SymPy available")
    ap.add_argument("--no-plots", action="store_true")
    ap.add_argument("--save-png")
    ap.add_argument("--no-show", action="store_true")
    ap.add_argument("-v","--verbose", action="count", default=0)
    return ap

def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="sphinx-skel", description="Create a minimal Sphinx docs skeleton.")
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    ap.add_argument("--force", action="store_true", help="Overwrite existing files if present")
    return ap

def main(argv: Optional[list[str]] = None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return

    # Normal run mode
    ap = _build_run_parser()
    args = ap.parse_args(argv)

    req = RunRequest(
        num=parse_coeffs(args.num),
        den=parse_coeffs(args.den),
        tfinal=args.tfinal,
        dt=args.dt,
        symbolic=args.symbolic,
        plots=not args.no_plots,
        save_png=args.save_png,
        no_show=args.no_show
    )
    app = CanonicalApp(level=_level(args.verbose))
    res = app.run(req)

    print("\n== Canonical Conversion Summary ==")
    print(f"G(s) = {res.pretty_tf}")
    print(f"OCF == CCF ? {res.equal_ocf}")
    print(f"Modal == CCF ? {res.equal_modal}")

    if req.symbolic:
        try:
            import sympy as sp
            s = sp.symbols('s')
            A, B, C, D = res.sys_ccf.A, res.sys_ccf.B, res.sys_ccf.C, res.sys_ccf.D
            As, Bs, Cs, Ds = sp.Matrix(A), sp.Matrix(B), sp.Matrix(C), sp.Matrix(D)
            Gs = sp.simplify(Cs * (s*sp.eye(As.shape[0]) - As)**-1 * Bs + Ds)
            print("\nSymbolic G(s):")
            print(sp.simplify(Gs[0,0]))
        except Exception as e:
            print("[symbolic] skipped:", e)

    app.render(req, res)

if __name__ == "__main__":
    main()
