# Generated by frequency_response.compensatorTool.cli
import sys
from pathlib import Path
# docs -> compensatorTool -> frequency_response -> <repo root>
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
project = 'modernControl - frequency_response.compensatorTool'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'furo'
