# root_locus_analysis/systemResponseTool/cli.py
from __future__ import annotations

# -------------------- sanitize argv ASAP --------------------
import sys as _sys
import os as _os
from pathlib import Path as _Path


def _sanitize_argv_and_capture_legacy_log(argv: list[str]) -> list[str]:
    """
    Accept legacy '--log LEVEL' while removing it from argv before Click sees it.

    The captured LEVEL is stored in the SRT_LOG_LEVEL environment variable for
    later use by the run command.
    """
    if _os.environ.get("SRT_TEST_NOISE"):
        print("[cli] pre-sanitize argv:", argv)

    if "--log" not in argv:
        return argv

    try:
        i = argv.index("--log")
        level = "INFO"
        if i + 1 < len(argv) and not argv[i + 1].startswith("-"):
            level = argv[i + 1]
            argv = argv[:i] + argv[i + 2 :]
        else:
            argv = argv[:i] + argv[i + 1 :]
        _os.environ["SRT_LOG_LEVEL"] = level
    except Exception:
        i = argv.index("--log")
        argv = argv[:i] + argv[i + 1 :]

    if _os.environ.get("SRT_TEST_NOISE"):
        print("[cli] post-sanitize argv:", argv)
        print("[cli] SRT_LOG_LEVEL env:", _os.environ.get("SRT_LOG_LEVEL"))

    return argv


_sys.argv = _sanitize_argv_and_capture_legacy_log(list(_sys.argv))

# ------------- import shim for 'python cli.py ...' -------------
if __package__ in (None, ""):
    _pkg_root = _os.path.abspath(_os.path.join(_os.path.dirname(__file__), "..", ".."))
    if _pkg_root not in _sys.path:
        _sys.path.insert(0, _pkg_root)
    from root_locus_analysis.systemResponseTool.apis import RunRequest, SystemResponseService
    from root_locus_analysis.systemResponseTool.utils import make_logger
    if _os.environ.get("SRT_TEST_NOISE"):
        print("[cli] import mode: script (__package__ empty). pkg_root=", _pkg_root)
else:
    from .apis import RunRequest, SystemResponseService
    from .utils import make_logger
    if _os.environ.get("SRT_TEST_NOISE"):
        print("[cli] import mode: package (__package__=", __package__, ")")

# Now it is safe to import third-party libraries that might inspect argv.
import logging as _logging
import click


# -------------------------- Sphinx skeleton helper --------------------------

_PACKAGE = "root_locus_analysis.systemResponseTool"
_PROJECT = "modernControl - root_locus_analysis.systemResponseTool"


def _rst_title(text: str, marker: str = "=") -> str:
    """Return a valid reStructuredText title with a safe underline length."""
    return f"{text}\n{marker * len(text)}\n\n"


def _rst_section(text: str, marker: str = "-") -> str:
    """Return a valid reStructuredText section heading."""
    return f"{text}\n{marker * len(text)}\n\n"


def _write_if_needed(path: _Path, text: str, *, force: bool = False) -> None:
    if path.exists() and not force:
        return
    path.write_text(text, encoding="utf-8")


def _ensure_support_dirs(dest: _Path) -> None:
    """Create Sphinx support directories and gitkeep files for deployment."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _write_sphinx_skel(dest: _Path, force: bool = False) -> _Path:
    """Create a minimal, deploy-safe Sphinx documentation skeleton."""
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_support_dirs(dest)

    conf = (
        "# Generated by root_locus_analysis.systemResponseTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> systemResponseTool -> root_locus_analysis -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n\n"
        f"project = {_PROJECT!r}\n"
        "author = 'modernControl'\n\n"
        "extensions = [\n"
        "    'sphinx.ext.autodoc',\n"
        "    'sphinx.ext.napoleon',\n"
        "    'sphinx.ext.viewcode',\n"
        "]\n\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']\n"
        "html_theme = 'furo'\n"
        "html_static_path = ['_static']\n\n"
        "autodoc_typehints = 'description'\n"
        "napoleon_google_docstring = True\n"
        "napoleon_numpy_docstring = True\n"
    )

    title = "Welcome to root_locus_analysis.systemResponseTool's docs!"
    index = (
        ".. root_locus_analysis.systemResponseTool documentation master file\n\n"
        + _rst_title(title)
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )

    api = (
        _rst_title("API Reference")
        + _rst_section("Application Layer")
        + ".. automodule:: root_locus_analysis.systemResponseTool.app\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_section("API Schemas and Services")
        + ".. automodule:: root_locus_analysis.systemResponseTool.apis\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_section("Core Utilities")
        + ".. automodule:: root_locus_analysis.systemResponseTool.utils\n"
        + "   :members:\n"
        + "   :undoc-members:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    _write_if_needed(dest / "conf.py", conf, force=force)
    _write_if_needed(dest / "index.rst", index, force=force)
    _write_if_needed(dest / "api.rst", api, force=force)
    _write_if_needed(dest / "Makefile", makefile, force=force)
    return dest


# ------------------------------- Click CLI ---------------------------------


@click.group(help="System response tool (step, ramp, impulse, arb, ic1, ic2).")
def cli():
    """Entry point for the systemResponseTool CLI."""
    pass


@cli.command("sphinx-skel", help="Create a minimal Sphinx docs skeleton for systemResponseTool.")
@click.argument("dest", required=False, default="docs")
@click.option("--force", is_flag=True, help="Overwrite existing generated files if present.")
def sphinx_skel_cmd(dest: str, force: bool) -> None:
    """Create Sphinx documentation files for this package."""
    out = _write_sphinx_skel(_Path(dest), force=force)
    click.echo(str(out))


@cli.command("run", help="Run responses for one or more systems.")
@click.option(
    "--sys", "sys_args", multiple=True, required=True,
    help="System spec string; repeat for multiple. See README or examples."
)
@click.option(
    "--responses", required=True,
    help="Comma/space list: step,ramp,impulse,arb,ic1,ic2"
)
@click.option("--tfinal", type=float, default=5.0, show_default=True)
@click.option("--dt", type=float, default=0.005, show_default=True)
@click.option("--title", type=str, default="")
@click.option("--out-prefix", type=str, default="")
@click.option("--show-input", is_flag=True, help="Overlay input for ramp/arb plots.")
@click.option(
    "--arb-kind", type=click.Choice(["ramp", "sine", "square", "expr", "file"]),
    default="ramp", show_default=True
)
@click.option("--arb-amp", type=float, default=1.0, show_default=True)
@click.option("--arb-freq", type=float, default=0.5, show_default=True)
@click.option("--arb-duty", type=float, default=0.5, show_default=True)
@click.option(
    "--arb-expr", type=str,
    default="sin(2*pi*0.5*t)+0.3*sin(2*pi*2*t)", show_default=True
)
@click.option("--arb-file", type=str, default="")
@click.option(
    "--ic-compare/--no-ic-compare", default=True, show_default=True,
    help="Overlay step-equivalent curves for IC modes."
)
@click.option(
    "--log", "legacy_log_level",
    type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"]),
    default=None, help="(legacy) use --log-level instead.", hidden=True
)
@click.option(
    "--log-level", "log_level",
    type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"]),
    default="INFO", show_default=True,
    help="Logging verbosity. Legacy '--log LEVEL' is also accepted."
)
def run(
    sys_args,
    responses,
    tfinal,
    dt,
    title,
    out_prefix,
    show_input,
    arb_kind,
    arb_amp,
    arb_freq,
    arb_duty,
    arb_expr,
    arb_file,
    ic_compare,
    legacy_log_level,
    log_level,
):
    """Execute requested response simulations for provided system specifications."""
    effective_level = (
        _os.environ.get("SRT_LOG_LEVEL")
        or legacy_log_level
        or log_level
    )

    if _os.environ.get("SRT_TEST_NOISE"):
        print("[cli.run] legacy_log_level =", legacy_log_level)
        print("[cli.run] log_level        =", log_level)
        print("[cli.run] effective_level  =", effective_level)
        print("[cli.run] CWD              =", _os.getcwd())
        print("[cli.run] in/out dirs will be package local ./in, ./out")

    logger = make_logger("systemResponseTool")
    logger.setLevel(getattr(_logging, str(effective_level), _logging.INFO))

    pkg_dir = _Path(__file__).resolve().parent
    in_dir = pkg_dir / "in"
    out_dir = pkg_dir / "out"

    resp_list = [r.strip().lower() for r in responses.replace(",", " ").split() if r.strip()]
    req = RunRequest(
        sys_args=list(sys_args),
        responses=resp_list,
        tfinal=tfinal,
        dt=dt,
        title=title,
        out_prefix=(out_prefix or None),
        arb_kind=arb_kind,
        arb_amp=arb_amp,
        arb_freq=arb_freq,
        arb_duty=arb_duty,
        arb_expr=arb_expr,
        arb_file=arb_file,
        show_input=show_input,
        ic_compare=ic_compare,
    )

    show_plots = not bool(_os.environ.get("PYTEST_CURRENT_TEST"))

    svc = SystemResponseService(in_dir, out_dir, show_plots=show_plots)
    svc.run(req)


if __name__ == "__main__":
    cli()
