# Generated by root_locus_analysis.compensatorTool.cli
import sys
from pathlib import Path

# docs -> compensatorTool -> root_locus_analysis -> <repo root>
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = 'modernControl - root_locus_analysis.compensatorTool'
author = 'modernControl'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'furo'
html_static_path = ['_static']
autodoc_typehints = 'description'
napoleon_google_docstring = True
napoleon_numpy_docstring = True
