#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from within the package folder.
    # Add project root to sys.path (../../)
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    # Import absolute modules
    from frequencyResponse.bodeTool.apis import BodeConfig
    from frequencyResponse.bodeTool.app import BodeApp
else:
    # Normal package execution (e.g., `python -m frequencyResponse.bodeTool.cli`)
    from .apis import BodeConfig
    from .app import BodeApp


def _level(v: int):
    return logging.DEBUG if v >= 2 else (logging.INFO if v == 1 else logging.INFO)


# -------------------------- Sphinx skeleton helper --------------------------

def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    """
    Create a minimal Sphinx docs skeleton under ``dest``.

    Files written:
      - conf.py (adds repo root to sys.path for autodoc)
        and sets project name.
      - index.rst
      - api.rst (autodoc for app & apis)
      - Makefile (make html / clean)

    ``dest`` is created if it doesn't exist.
    """
    dest.mkdir(parents=True, exist_ok=True)

    conf = (
        "# Generated by frequencyResponse.bodeTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> bodeTool -> frequencyResponse -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n"
        "project = 'modernControl – frequencyResponse.bodeTool'\n"
        "extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = []\n"
        "html_theme = 'furo'\n"
    )

    index = (
        ".. frequencyResponse.bodeTool documentation master file\n\n"
        "Welcome to frequencyResponse.bodeTool's docs!\n"
        "=============================================\n\n"
        ".. toctree::\n"
        "   :maxdepth: 2\n"
        "   :caption: Contents:\n\n"
        "   api\n"
    )

    api = (
        "API Reference\n"
        "=============\n\n"
        ".. automodule:: frequencyResponse.bodeTool.app\n"
        "   :members:\n"
        "   :undoc-members:\n\n"
        ".. automodule:: frequencyResponse.bodeTool.apis\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: frequencyResponse.bodeTool.core\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: frequencyResponse.bodeTool.io\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: frequencyResponse.bodeTool.utils\n"
        "   :members:\n"
        "   :undoc-members:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    def _write(path: Path, text: str):
        if path.exists() and not force:
            return
        path.write_text(text, encoding="utf-8")

    (dest / "_templates").mkdir(exist_ok=True)
    (dest / "_static").mkdir(exist_ok=True)
    _write(dest / "conf.py", conf)
    _write(dest / "index.rst", index)
    _write(dest / "api.rst", api)
    _write(dest / "Makefile", makefile)
    return dest


# ------------------------------ CLI parsers --------------------------------

def _build_run_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Bode/Nyquist/Nichols with margins, bandwidth, resonant peak.")
    # G(s) inputs
    ap.add_argument("--num"); ap.add_argument("--den")
    ap.add_argument("--gain", type=float); ap.add_argument("--zeros"); ap.add_argument("--poles")
    ap.add_argument("--fnum"); ap.add_argument("--fden"); ap.add_argument("--K", type=float, default=1.0)
    # H(s)
    ap.add_argument("--hnum"); ap.add_argument("--hden")
    ap.add_argument("--hgain", type=float); ap.add_argument("--hzeros"); ap.add_argument("--hpoles")
    ap.add_argument("--hfnum"); ap.add_argument("--hfden"); ap.add_argument("--hK", type=float, default=1.0)
    # frequency grid
    ap.add_argument("--wmin", type=float); ap.add_argument("--wmax", type=float); ap.add_argument("--npts", type=int, default=2000)
    # plots/exports
    ap.add_argument("--bode", action="store_true"); ap.add_argument("--nyquist", action="store_true"); ap.add_argument("--nichols", action="store_true")
    ap.add_argument("--step", action="store_true"); ap.add_argument("--plotly", action="store_true")
    ap.add_argument("--save-png"); ap.add_argument("--save-html"); ap.add_argument("--save-json")
    ap.add_argument("--title", default="Bode of L(s)")
    ap.add_argument("-v","--verbose", action="count", default=0)
    return ap


def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="sphinx-skel", description="Create a minimal Sphinx docs skeleton.")
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    ap.add_argument("--force", action="store_true", help="Overwrite existing files if present")
    return ap


def main(argv: Optional[list[str]] = None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] == "sphinx-skel":
        # Handle the docs helper subcommand
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return

    # Normal run mode
    ap = _build_run_parser()
    args = ap.parse_args(argv)

    cfg = BodeConfig(
        num=args.num, den=args.den, gain=args.gain, zeros=args.zeros, poles=args.poles,
        fnum=args.fnum, fden=args.fden, K=args.K,
        hnum=args.hnum, hden=args.hden, hgain=args.hgain, hzeros=args.hzeros, hpoles=args.hpoles,
        hfnum=args.hfnum, hfden=args.hfden, hK=args.hK,
        wmin=args.wmin, wmax=args.wmax, npts=args.npts,
        bode=args.bode, nyquist=args.nyquist, nichols=args.nichols, step=args.step, plotly=args.plotly,
        save_png=args.save_png, save_html=args.save_html, save_json=args.save_json,
        title=args.title, verbose=args.verbose
    )
    app = BodeApp(level=_level(cfg.verbose))
    result = app.run(cfg)
    print("\n== Frequency-Response Summary ==")
    print(f"L(s) = {result.pretty_tf}")
    print(f"Gain margin      : {result.margins.gm:.6g}  ({result.margins.gm_db:.3g} dB) at w_pc = {result.margins.wpc:.6g} rad/s")
    print(f"Phase margin     : {result.margins.pm:.6g} deg at w_gc = {result.margins.wgc:.6g} rad/s")
    print(f"Closed-loop Mr   : {result.closedloop.Mr_db:.3g} dB at w_r = {result.closedloop.wr:.6g} rad/s")
    print(f"Closed-loop w_bw : {result.closedloop.wb:.6g} rad/s")
    print("Hints:"); [print(" •", h) for h in result.hints]
    app.render(cfg, result)


if __name__ == "__main__":
    main()
