from __future__ import annotations

import os
import sys
from pathlib import Path

import click

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_analysis/canonicalTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_analysis.canonicalTool.utils import parse_list
    from state_space_analysis.canonicalTool.design import CompareOptions
    from state_space_analysis.canonicalTool.app import CanonicalToolApp
    from state_space_analysis.canonicalTool.io import default_out_path
else:
    from .utils import parse_list
    from .design import CompareOptions
    from .app import CanonicalToolApp
    from .io import default_out_path


_PACKAGE = "state_space_analysis.canonicalTool"
_PROJECT = "modernControl - state_space_analysis.canonicalTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_analysis.canonicalTool.cli",
    "state_space_analysis.canonicalTool.apis",
    "state_space_analysis.canonicalTool.app",
    "state_space_analysis.canonicalTool.core",
    "state_space_analysis.canonicalTool.design",
    "state_space_analysis.canonicalTool.io",
    "state_space_analysis.canonicalTool.utils",
]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Build a reStructuredText heading with a matching underline."""
    safe = str(text).rstrip()
    marker = underline[:1] if underline else "="
    return f"{safe}\n{marker * len(safe)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write a file unless it already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create support directories and gitkeep files for Sphinx."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> canonicalTool -> state_space_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with safe heading lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build a simple API reference page."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal Sphinx Makefile used across the project."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update the Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


@click.group(help="canonicalTool - SISO canonical forms analysis for CCF, OCF, and modal forms.")
def cli() -> None:
    """Command line interface for canonical form analysis."""
    pass


@cli.command("compare", help="Compare CCF, OCF, and modal forms and plot step responses.")
@click.option(
    "--num",
    type=str,
    default="2,3",
    show_default=True,
    help="Numerator coefficients in descending powers.",
)
@click.option(
    "--den",
    type=str,
    default="1,1,10",
    show_default=True,
    help="Denominator coefficients in descending powers.",
)
@click.option("--tfinal", type=float, default=8.0, show_default=True)
@click.option("--dt", type=float, default=1e-3, show_default=True)
@click.option(
    "--symbolic/--no-symbolic",
    default=False,
    show_default=True,
    help="Print the symbolic transfer function when SymPy is available.",
)
@click.option(
    "--backend",
    type=click.Choice(["mpl", "plotly"], case_sensitive=False),
    default="mpl",
    show_default=True,
)
@click.option("--no_show", is_flag=True, help="Disable graphical display.")
@click.option(
    "--save",
    type=str,
    default=default_out_path("canonical_compare_{kind}.png"),
    show_default=True,
    help="Output path. The value may include a kind token such as step.",
)
def compare(
    num: str,
    den: str,
    tfinal: float,
    dt: float,
    symbolic: bool,
    backend: str,
    no_show: bool,
    save: str,
) -> None:
    """Run a canonical form comparison for a SISO transfer function."""
    num_v = parse_list(num)
    den_v = parse_list(den)
    app = CanonicalToolApp()
    opts = CompareOptions(
        tfinal=tfinal,
        dt=dt,
        symbolic=symbolic,
        backend=backend,
        show=(not no_show),
        save=save,
    )
    res = app.compare(num=num_v, den=den_v, opts=opts)

    click.echo("TF equality (vs CCF):")
    for k, v in res.tf_equal.items():
        click.echo(f"  {k}: {v}")

    if res.symbolic is not None:
        click.echo("\nSymbolic G(s):")
        click.echo(res.symbolic)


@cli.command("sphinx-skel", help="Create a deploy-safe Sphinx documentation skeleton for this package.")
@click.argument("dest", type=click.Path(file_okay=False, dir_okay=True, path_type=Path))
@click.option("--force", is_flag=True, help="Overwrite existing Sphinx skeleton files.")
def sphinx_skel(dest: Path, force: bool) -> None:
    """Generate Sphinx files with safe headings and tracked support folders."""
    written = _write_sphinx_skeleton(dest, force=force)
    click.echo(f"Sphinx skeleton ready: {dest}")
    if written:
        click.echo("Written files:")
        for path in written:
            click.echo(f"  {path}")
    else:
        click.echo("No existing files were overwritten. Use --force to regenerate.")
    click.echo("Support files ensured:")
    click.echo(f"  {dest / '_static' / '.gitkeep'}")
    click.echo(f"  {dest / '_templates' / '.gitkeep'}")


def main() -> None:
    """Run the canonicalTool command line interface."""
    cli()


if __name__ == "__main__":
    main()
