# Generated by control_systems.canonicalTool.cli
import sys
from pathlib import Path
# docs -> canonicalTool -> control_systems -> <repo root>
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
project = 'modernControl – control_systems.canonicalTool'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'furo'
