#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Command line interface for the LQR tool."""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
from pathlib import Path

import numpy as np

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/lqrTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.lqrTool.apis import LQRRunRequest
    from state_space_design.lqrTool.app import LQRApp
    from state_space_design.lqrTool.core import Simulator
    from state_space_design.lqrTool.io import parse_vector, parse_Q, parse_R
    from state_space_design.lqrTool.plotting import (
        plot_mpl_initial,
        plot_mpl_step,
        plot_plotly_initial,
        plot_plotly_step,
    )
else:
    from .apis import LQRRunRequest
    from .app import LQRApp
    from .core import Simulator
    from .io import parse_vector, parse_Q, parse_R
    from .plotting import (
        plot_mpl_initial,
        plot_mpl_step,
        plot_plotly_initial,
        plot_plotly_step,
    )


_PACKAGE = "state_space_design.lqrTool"
_PROJECT = "modernControl - state_space_design.lqrTool"
_AUTHOR = "modernControl"
_BASE_MODULES = [
    "state_space_design.lqrTool.cli",
    "state_space_design.lqrTool.apis",
    "state_space_design.lqrTool.app",
    "state_space_design.lqrTool.core",
    "state_space_design.lqrTool.io",
    "state_space_design.lqrTool.plotting",
]

# When running from inside lqrTool, write artifacts to ./out by default.
OUT_DIR = "out"


def _module_exists(module_name: str) -> bool:
    """Return true when a module can be found by Python import machinery."""
    return importlib.util.find_spec(module_name) is not None


def _real_modules() -> list[str]:
    """Return only modules that are importable to avoid Sphinx ghost-module failures."""
    return [module for module in _BASE_MODULES if _module_exists(module)]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> lqrTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _real_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _normalize_argv(argv: list[str] | None) -> list[str] | None:
    """Normalize command line arguments before argparse handles them."""
    return argv


def _ensure_prefix_dir(prefix: str | None) -> str | None:
    """Place basename-only plot prefixes under the package-local output folder."""
    if not prefix:
        return None
    dname = os.path.dirname(prefix)
    if not dname:
        os.makedirs(OUT_DIR, exist_ok=True)
        return os.path.join(OUT_DIR, prefix)
    os.makedirs(dname, exist_ok=True)
    return prefix


def _json_default(o):
    """JSON fallback for NumPy scalars and complex values."""
    try:
        import numpy as _np
        if isinstance(o, _np.generic):
            return o.item()
    except Exception:
        pass
    if isinstance(o, complex):
        return [float(o.real), float(o.imag)]
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")


def build_parser() -> argparse.ArgumentParser:
    """Build the command line parser."""
    parser = argparse.ArgumentParser(
        prog="state_space_design.lqrTool",
        description="LQR design and simulation tool for state-space systems.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run an LQR design and optional simulations",
        description="Run an LQR design and optional initial-condition or step simulations.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    g_sys = run.add_argument_group("System definition")
    g_sys.add_argument("--A", type=str, help='State matrix, for example "0 1; 0 -1".')
    g_sys.add_argument("--B", type=str, help='Input matrix, for example "0; 1".')
    g_sys.add_argument("--C", type=str, help="Output matrix. The default is y = x1.")
    g_sys.add_argument("--D", type=str, default="0", help="Direct term.")
    g_sys.add_argument("--num", type=str, help='Transfer-function numerator, for example "1, 2".')
    g_sys.add_argument("--den", type=str, help='Transfer-function denominator, for example "1, 3, 2".')

    g_w = run.add_argument_group("Weights")
    g_w.add_argument(
        "--Q",
        type=str,
        default="eye",
        help='Q weighting: "eye", "eye:n", "diag:q1,q2", or a matrix string.',
    )
    g_w.add_argument("--R", type=str, default="1", help="R weighting as a scalar or matrix string.")

    g_s = run.add_argument_group("Simulations")
    g_s.add_argument("--x0", type=str, default=None, help='Initial state, for example "1 1".')
    g_s.add_argument("--step", action="store_true", help="Run a unit-step tracking simulation.")
    g_s.add_argument("--step_amp", type=float, default=1.0, help="Step amplitude.")
    g_s.add_argument(
        "--prefilter",
        type=str,
        default="dcgain",
        choices=["ogata", "dcgain", "none"],
        help="Servo prefilter mode.",
    )
    g_s.add_argument("--tfinal", type=float, default=8.0, help="Simulation length in seconds.")
    g_s.add_argument("--dt", type=float, default=0.01, help="Simulation time step in seconds.")

    g_o = run.add_argument_group("Output")
    g_o.add_argument(
        "--plots",
        type=str,
        default="mpl",
        choices=["mpl", "plotly", "both", "none"],
        help="Plot backend.",
    )
    g_o.add_argument(
        "--export_json",
        type=str,
        default=None,
        help="Path to write JSON summary data.",
    )
    g_o.add_argument(
        "--save_prefix",
        type=str,
        default=None,
        help="Prefix for plot files. Basename-only values are stored under the output folder.",
    )
    g_o.add_argument("--no_show", action="store_true", help="Do not display interactive plot windows.")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_lqr(args: argparse.Namespace) -> int:
    req = LQRRunRequest(
        A=args.A,
        B=args.B,
        C=args.C,
        D=args.D,
        num=args.num,
        den=args.den,
        Q=args.Q,
        R=args.R,
        x0=args.x0,
        step=bool(args.step),
        step_amp=args.step_amp,
        prefilter=args.prefilter,
        tfinal=args.tfinal,
        dt=args.dt,
        plots=args.plots,
    )
    app = LQRApp(req)
    res = app.run()

    model = app.build_model()
    t = np.arange(0.0, req.tfinal + 1e-12, req.dt)
    x0 = parse_vector(req.x0) if req.x0 else None
    save_prefix = _ensure_prefix_dir(args.save_prefix)

    if x0 is not None:
        traj_ic = Simulator.initial(model, np.asarray(res.K), x0, t)
        if args.plots in ("mpl", "both"):
            fig = plot_mpl_initial(traj_ic.T, traj_ic.X, traj_ic.Y, traj_ic.U)
            if save_prefix:
                fig.savefig(f"{save_prefix}_ic.png", dpi=150)
            if not args.no_show:
                import matplotlib.pyplot as plt
                plt.show()
        if args.plots in ("plotly", "both"):
            fig = plot_plotly_initial(traj_ic.T, traj_ic.X, traj_ic.Y, traj_ic.U)
            if save_prefix:
                fig.write_html(f"{save_prefix}_ic.html", include_plotlyjs="cdn")
            if not args.no_show:
                fig.show()

    if req.step:
        N = res.prefilter_gain or 0.0
        traj_st = Simulator.forced_step(model, np.asarray(res.K), float(N), t, amp=req.step_amp)
        if args.plots in ("mpl", "both"):
            fig = plot_mpl_step(traj_st.T, traj_st.X, traj_st.Y, traj_st.U)
            if save_prefix:
                fig.savefig(f"{save_prefix}_step.png", dpi=150)
            if not args.no_show:
                import matplotlib.pyplot as plt
                plt.show()
        if args.plots in ("plotly", "both"):
            fig = plot_plotly_step(traj_st.T, traj_st.X, traj_st.Y, traj_st.U)
            if save_prefix:
                fig.write_html(f"{save_prefix}_step.html", include_plotlyjs="cdn")
            if not args.no_show:
                fig.show()

    if args.export_json:
        export_path = args.export_json
        dirname = os.path.dirname(export_path)
        if dirname and not os.path.exists(dirname):
            os.makedirs(dirname, exist_ok=True)
        with open(export_path, "w", encoding="utf-8") as f:
            json.dump(res.to_jsonable(), f, indent=2, default=_json_default)

    print(json.dumps(res.to_jsonable(), indent=2, default=_json_default))
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = _normalize_argv(list(argv) if argv is not None else None)
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility: allow historical no-subcommand usage.
    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_lqr(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
