#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from modeling_control_systems.systemTool.apis import RunConfig, MSDConfig, TFfromSSConfig, ODENoDerivConfig, ODEWithDerivConfig, CommonSim
    from modeling_control_systems.systemTool.app import SystemModelingApp
else:
    from .apis import RunConfig, MSDConfig, TFfromSSConfig, ODENoDerivConfig, ODEWithDerivConfig, CommonSim
    from .app import SystemModelingApp

def _level(v: int) -> int:
    return logging.DEBUG if v >= 2 else (logging.INFO if v == 1 else logging.INFO)

# -------------------------- Sphinx skeleton helper --------------------------
def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    dest.mkdir(parents=True, exist_ok=True)
    conf = """# Generated by modeling_control_systems.systemTool.cli
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
project = 'modernControl – modeling_control_systems.systemTool'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'furo'
"""
    index = """.. modeling_control_systems.systemTool documentation master file

Welcome to modeling_control_systems.systemTool's docs!
============================================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   api
"""
    api = """API Reference
=============

.. automodule:: modeling_control_systems.systemTool.app
   :members:
   :undoc-members:

.. automodule:: modeling_control_systems.systemTool.apis
   :members:
   :undoc-members:

.. automodule:: modeling_control_systems.systemTool.core
   :members:
   :undoc-members:

.. automodule:: modeling_control_systems.systemTool.io
   :members:
   :undoc-members:

.. automodule:: modeling_control_systems.systemTool.design
   :members:
   :undoc-members:

.. automodule:: modeling_control_systems.systemTool.utils
   :members:
   :undoc-members:
"""
    makefile = """# Minimal Sphinx Makefile
.PHONY: html clean
html:
\t+sphinx-build -b html . _build/html
clean:
\t+rm -rf _build
"""
    (dest / "_templates").mkdir(exist_ok=True)
    (dest / "_static").mkdir(exist_ok=True)

    def _write(path: Path, text: str) -> None:
        if path.exists() and not force:
            return
        path.write_text(text, encoding="utf-8")

    _write(dest / "conf.py", conf)
    _write(dest / "index.rst", index)
    _write(dest / "api.rst", api)
    _write(dest / "Makefile", makefile)
    return dest

# ------------------------------ CLI parsers --------------------------------
def _build_run_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="System modeling toolkit (Ogata ch. 2).")
    sub = ap.add_subparsers(dest="mode", required=True)

    # msd-step
    msd = sub.add_parser("msd-step", help="Mass–spring–damper step response.")
    msd.add_argument("--m", type=float, default=1.0)
    msd.add_argument("--b", type=float, default=1.0)
    msd.add_argument("--k", type=float, default=10.0)
    msd.add_argument("--y0", type=float, default=0.0)
    msd.add_argument("--ydot0", type=float, default=0.0)
    msd.add_argument("--u0", type=float, default=1.0)
    msd.add_argument("--tfinal", type=float, default=10.0)
    msd.add_argument("--dt", type=float, default=1e-3)
    msd.add_argument("--no-save", action="store_true")
    msd.add_argument("-v", "--verbose", action="count", default=0)

    # tf-from-ss
    tfss = sub.add_parser("tf-from-ss", help="Compute G(s) from (A,B,C,D).")
    tfss.add_argument("--A")
    tfss.add_argument("--B")
    tfss.add_argument("--C")
    tfss.add_argument("--D")
    tfss.add_argument("--m", type=float, default=1.0)
    tfss.add_argument("--b", type=float, default=1.0)
    tfss.add_argument("--k", type=float, default=10.0)
    tfss.add_argument("-v", "--verbose", action="count", default=0)

    # mimo-demo
    mimo = sub.add_parser("mimo-demo", help="2x2 demo with steps.")
    mimo.add_argument("-v", "--verbose", action="count", default=0)

    # ode-no-deriv
    ond = sub.add_parser("ode-no-deriv", help="Companion form for y^(n)+... (no u-deriv).")
    ond.add_argument("--a", help='"[a1,...,an]"')
    ond.add_argument("--b0", type=float, default=1.0)
    ond.add_argument("--msd", action="store_true")
    ond.add_argument("--m", type=float, default=1.0)
    ond.add_argument("--b", type=float, default=1.0)
    ond.add_argument("--k", type=float, default=10.0)
    ond.add_argument("--y0", type=float, default=0.0)
    ond.add_argument("--ydot0", type=float, default=0.0)
    ond.add_argument("--u0", type=float, default=1.0)
    ond.add_argument("--tfinal", type=float, default=10.0)
    ond.add_argument("--dt", type=float, default=1e-3)
    ond.add_argument("--no-save", action="store_true")
    ond.add_argument("-v", "--verbose", action="count", default=0)

    # ode-with-deriv
    od = sub.add_parser("ode-with-deriv", help="Ogata beta construction for u-derivatives in forcing.")
    od.add_argument("--a", help='"[a1,...,an]"')
    od.add_argument("--b", help='"[b0,...,bn]"')
    od.add_argument("--u0", type=float, default=1.0)
    od.add_argument("--tfinal", type=float, default=8.0)
    od.add_argument("--dt", type=float, default=1e-3)
    od.add_argument("--no-save", action="store_true")
    od.add_argument("-v", "--verbose", action="count", default=0)

    # kv-vs-maxwell
    kv = sub.add_parser("kv-vs-maxwell", help="Compare Kelvin–Voigt vs Maxwell (y overlays).")
    kv.add_argument("--u0", type=float, default=1.0)
    kv.add_argument("--tfinal", type=float, default=10.0)
    kv.add_argument("--dt", type=float, default=1e-3)
    kv.add_argument("--no-save", action="store_true")
    kv.add_argument("-v", "--verbose", action="count", default=0)

    # docs helper
    sph = sub.add_parser("sphinx-skel", help="Create a minimal Sphinx docs skeleton.")
    sph.add_argument("dest", nargs="?", default="docs")
    sph.add_argument("--force", action="store_true")

    return ap

def main(argv: Optional[list[str]] = None) -> None:
    ap = _build_run_parser()
    ns = ap.parse_args(argv)

    if ns.mode == "sphinx-skel":
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return

    if ns.mode == "msd-step":
        cfg = RunConfig(
            mode="msd-step",
            msd=MSDConfig(
                m=ns.m, b=ns.b, k=ns.k, y0=ns.y0, ydot0=ns.ydot0,
                u0=ns.u0, tfinal=ns.tfinal, dt=ns.dt, save=not ns.no_save, verbose=ns.verbose
            ),
        )
    elif ns.mode == "tf-from-ss":
        cfg = RunConfig(mode="tf-from-ss", tfss=TFfromSSConfig(A=ns.A, B=ns.B, C=ns.C, D=ns.D, m=ns.m, b=ns.b, k=ns.k))
    elif ns.mode == "mimo-demo":
        cfg = RunConfig(mode="mimo-demo")
    elif ns.mode == "ode-no-deriv":
        cfg = RunConfig(
            mode="ode-no-deriv",
            ode_nd=ODENoDerivConfig(
                a=ns.a, b0=ns.b0, msd=ns.msd, m=ns.m, b=ns.b, k=ns.k,
                y0=ns.y0, ydot0=ns.ydot0, u0=ns.u0, tfinal=ns.tfinal, dt=ns.dt,
                save=not ns.no_save, verbose=ns.verbose
            ),
        )
    elif ns.mode == "ode-with-deriv":
        cfg = RunConfig(
            mode="ode-with-deriv",
            ode_d=ODEWithDerivConfig(a=ns.a, b=ns.b, u0=ns.u0, tfinal=ns.tfinal, dt=ns.dt, save=not ns.no_save, verbose=ns.verbose),
        )
    elif ns.mode == "kv-vs-maxwell":
        cfg = RunConfig(
            mode="kv-vs-maxwell",
            kvmax=CommonSim(u0=ns.u0, tfinal=ns.tfinal, dt=ns.dt, save=not ns.no_save, verbose=ns.verbose),
        )
    else:
        ap.error(f"Unknown mode {ns.mode}")
        return

    app = SystemModelingApp(level=_level(getattr(ns, "verbose", 0)))
    result = app.run(cfg)
    print("ok" if result.ok else "error", "-", result.message)
    if result.pretty_tf:
        print("\n== Transfer Function(s) ==")
        print(result.pretty_tf)
    if result.saved_images:
        print("\n== Saved images ==")
        for p in result.saved_images:
            print(" ", p)
    if result.hints:
        print("\n== Hints ==")
        for h in result.hints:
            print(" •", h)

if __name__ == "__main__":
    main()
