from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/observerStatePlotTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.observerStatePlotTool.apis import PlotRequest, SimulateOptions
    from state_space_design.observerStatePlotTool.app import ObserverStatePlotApp
else:
    from .apis import PlotRequest, SimulateOptions
    from .app import ObserverStatePlotApp


_PACKAGE = "state_space_design.observerStatePlotTool"
_PROJECT = "modernControl - state_space_design.observerStatePlotTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "state_space_design.observerStatePlotTool.cli",
    "state_space_design.observerStatePlotTool.apis",
    "state_space_design.observerStatePlotTool.app",
]
_OPTIONAL_MODULES = [
    "state_space_design.observerStatePlotTool.core",
    "state_space_design.observerStatePlotTool.io",
    "state_space_design.observerStatePlotTool.plotting",
    "state_space_design.observerStatePlotTool.utils",
]


def _module_exists(module_name: str) -> bool:
    """Return true when Python can locate the module without importing it."""
    try:
        return importlib.util.find_spec(module_name) is not None
    except Exception:
        return False


def _doc_modules() -> list[str]:
    """Return the API modules that are safe for autodoc to import."""
    modules = list(_REQUIRED_MODULES)
    for module_name in _OPTIONAL_MODULES:
        if _module_exists(module_name):
            modules.append(module_name)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> observerStatePlotTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _doc_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="observerStatePlotTool",
        description="Observer and controller state plotter.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="plot observer and controller state data",
        description="Plot observer, controller, output, input, or error trajectories from exported JSON data.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    run.add_argument("--data", required=True, help="Observer gain matrix JSON with simulation data or an augmented state matrix.")
    run.add_argument("--what", default="auto", help="Comma-separated list from x, e, err, y, u, or auto.")
    run.add_argument("--subplots", action="store_true", help="Stack series as Ogata-style subplots.")
    run.add_argument("--backend", choices=["mpl", "plotly", "both", "none"], default="both", help="Plotting backend.")
    run.add_argument("--save_png", default=None, help="PNG filename. Defaults are handled by the package output directory.")
    run.add_argument("--save_html", default=None, help="Plotly HTML filename. Defaults are handled by the package output directory.")
    run.add_argument("--save_csv", default=None, help="CSV filename. Defaults are handled by the package output directory.")
    run.add_argument("--no_show", action="store_true", help="Do not show Matplotlib figures.")
    run.add_argument(
        "--simulate_if_missing",
        action="store_true",
        help="Simulate from the augmented state matrix when simulation data is missing.",
    )
    run.add_argument("--t", default="0:0.01:4", help="Time vector as t0:dt:tf, used when simulating.")
    run.add_argument("--x0", default=None, help="Initial plant state, used when simulating.")
    run.add_argument("--e0", default=None, help="Initial observer error, used when simulating.")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _strip_accidental_module_invocation(argv: list[str]) -> list[str]:
    """Remove accidental '-m module' tokens if a wrapper passed them through."""
    raw = list(argv)
    if "-m" in raw:
        try:
            i = raw.index("-m")
            del raw[i]
            if i < len(raw):
                del raw[i]
        except Exception:
            pass
    return raw


def _run_plot(args: argparse.Namespace) -> int:
    req = PlotRequest(
        data_path=args.data,
        what=args.what,
        backend=args.backend,
        subplots=args.subplots,
        save_png=args.save_png,
        save_html=args.save_html,
        save_csv=args.save_csv,
        no_show=args.no_show,
        simulate=SimulateOptions(
            enabled=args.simulate_if_missing,
            t=args.t,
            x0=args.x0,
            e0=args.e0,
        ),
    )

    # Allow the none backend for CSV-only exports.
    if req.backend == "none":
        req.backend = "mpl"
        req.no_show = True
        req.save_png = None
        req.save_html = None

    app = ObserverStatePlotApp()
    resp = app.run(req)
    if resp.csv_path:
        print(f"[OK] Wrote CSV: {resp.csv_path}")
    if resp.png_path:
        print(f"[OK] Wrote PNG: {resp.png_path}")
    if resp.html_path:
        print(f"[OK] Wrote HTML: {resp.html_path}")
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    raw = _strip_accidental_module_invocation(list(argv) if argv is not None else list(sys.argv[1:]))
    args = parser.parse_args(raw)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility: allow the historical command shape without an
    # explicit run subcommand, for example: python cli.py --data run.json.
    if args.cmd is None:
        legacy_args = list(raw)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_plot(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
