# cli.py - CLI entry point for state_space_analysis.stepSolnTool
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_analysis/stepSolnTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_analysis.stepSolnTool.app import StateSolnApp
else:
    from .app import StateSolnApp


_PACKAGE = "state_space_analysis.stepSolnTool"
_PROJECT = "modernControl - state_space_analysis.stepSolnTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_analysis.stepSolnTool.cli",
    "state_space_analysis.stepSolnTool.apis",
    "state_space_analysis.stepSolnTool.app",
    "state_space_analysis.stepSolnTool.core",
    "state_space_analysis.stepSolnTool.io",
    "state_space_analysis.stepSolnTool.utils",
]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> stepSolnTool -> state_space_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Solve a state-space response from a SISO transfer function. "
            "The solver computes the transition matrix, homogeneous response, "
            "particular response, and full state solution."
        )
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="solve the state-space response for a transfer-function realization",
        description=(
            "Solve xdot = A x + B u from a SISO transfer function using the selected "
            "state-space realization."
        ),
    )

    g_in = run.add_argument_group("Input TF")
    g_in.add_argument("--tf", type=str, help='Rational string, for example "(s+3)/(s^2+3*s+2)".')
    g_in.add_argument("--num", type=str, help='Numerator as CSV "1,3" or polynomial text "s+3".')
    g_in.add_argument("--den", type=str, help='Denominator as CSV "1,3,2" or polynomial text "s^2+3*s+2".')
    g_in.add_argument("--example", type=str, choices=["ogata_9_1"], help="Use the built-in Ogata 9-1 transfer-function example.")

    g_opt = run.add_argument_group("Options")
    g_opt.add_argument(
        "--canonical",
        default="controllable",
        choices=["controllable", "observable", "diagonal", "jordan"],
        help="State-space realization used for the solution.",
    )
    g_opt.add_argument(
        "--u",
        type=str,
        default="1",
        help='Input u(t) as a SymPy expression in t. Examples: "1", "exp(-t)", "sin(2*t)".',
    )
    g_opt.add_argument("--x0", type=str, help="Initial state as CSV. The default is a zero vector.")
    g_opt.add_argument("--t0", type=float, default=0.0, help="Initial time. The default is 0.")
    g_opt.add_argument("--eval", type=float, help="Evaluate the state solution at this time.")
    g_opt.add_argument("--numeric", action="store_true", help="Print numeric values when an evaluation time is provided.")
    g_opt.add_argument("--digits", type=int, default=8, help="Digits for numeric printing.")
    g_opt.add_argument("--pretty", action="store_true", help="Pretty-print symbolic matrices when supported.")
    g_opt.add_argument("--export-json", type=str, help="Write the solution data to JSON.")
    g_opt.add_argument("--verify", action="store_true", help="Verify the differential equation and initial condition.")
    g_opt.add_argument("--tol", type=float, default=1e-9, help="Tolerance for numeric fallback during verification.")
    g_opt.add_argument("--log", type=str, default="INFO", help="Logging level.")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_solution(args: argparse.Namespace) -> int:
    app = StateSolnApp(canonical=args.canonical)
    app.configure_logging(args.log)

    result = app.run(
        tf=args.tf,
        num=args.num,
        den=args.den,
        example=args.example,
        u=args.u,
        x0=args.x0,
        t0=args.t0,
        eval_time=args.eval,
        numeric=args.numeric,
        digits=args.digits,
        pretty=args.pretty,
        verify=args.verify,
        tol=args.tol,
        export_json=args.export_json,
    )

    print(f"\n== Solution for xdot=Ax+Bu ({args.canonical}) ==")
    print(f"A =\n{result['A']}")
    print(f"\nB =\n{result['B']}")
    print(f"\nPhi(t) =\n{result['Phi']}")
    print(f"\nx_hom =\n{result['x_hom']}")
    print(f"\nx_part =\n{result['x_part']}")
    print(f"\n   x(t) =\n{result['x']}")
    if result.get("verification"):
        print(f"\n[Verification] {result['verification']}")

    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility: allow the historical command shape without an
    # explicit "run" subcommand, for example: python cli.py --example ogata_9_1.
    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_solution(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
