# transient_analysis/responseTool/cli.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path

import numpy as np

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside transient_analysis/responseTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from transient_analysis.responseTool.utils import parse_matrix, parse_vector
    from transient_analysis.responseTool.app import ResponseToolApp
else:
    from .utils import parse_matrix, parse_vector
    from .app import ResponseToolApp


_PACKAGE = "transient_analysis.responseTool"
_PROJECT = "modernControl - transient_analysis.responseTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "transient_analysis.responseTool.cli",
    "transient_analysis.responseTool.app",
    "transient_analysis.responseTool.utils",
]
_OPTIONAL_MODULES = [
    "transient_analysis.responseTool.apis",
    "transient_analysis.responseTool.core",
    "transient_analysis.responseTool.io",
    "transient_analysis.responseTool.design",
    "transient_analysis.responseTool.plotting",
]


def _available_modules() -> list[str]:
    """Return importable modules so generated docs do not reference missing files."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it already exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> responseTool -> transient_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def parse_zetas_list(s: str | None) -> list[float]:
    """Parse a damping-ratio list and return a default grid when empty."""
    if not s:
        return [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    toks = [t for t in s.replace(",", " ").split() if t.strip()]
    return [float(t) for t in toks]


def parse_overlay_list(s: str | None) -> list[float]:
    """Parse an optional damping-ratio overlay list."""
    if not s:
        return []
    toks = [t for t in s.replace(",", " ").split() if t.strip()]
    return [float(t) for t in toks]


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        description=(
            "ResponseTool - unit ramp, arbitrary transfer-function input, "
            "MIMO state-space step, and second-order response exploration."
        ),
        conflict_handler="resolve",
        allow_abbrev=False,
    )

    parser.add_argument(
        "--root",
        default=None,
        help="I/O root. Default is the responseTool package directory.",
    )

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--root",
        default=argparse.SUPPRESS,
        help="I/O root. Default is the responseTool package directory.",
    )

    sub = parser.add_subparsers(dest="cmd", required=True)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    ramp = sub.add_parser(
        "ramp-ss",
        parents=[common],
        help="unit-ramp response through state-space augmentation",
    )
    ramp.add_argument("--A", type=str, default="0 1; -1 -1")
    ramp.add_argument("--B", type=str, default="0; 1")
    ramp.add_argument("--C", type=str, default="1 0")
    ramp.add_argument("--D", type=str, default="0")
    ramp.add_argument("--tfinal", type=float, default=10.0)
    ramp.add_argument("--dt", type=float, default=0.01)
    ramp.add_argument("--plot", action="store_true", help="Show and save plot.")

    lsim = sub.add_parser(
        "lsim-tf",
        parents=[common],
        help="simulate an arbitrary input for a transfer function",
    )
    lsim.add_argument("--num", type=str, default="2 1", help="Numerator coefficients in descending powers.")
    lsim.add_argument("--den", type=str, default="1 1 1", help="Denominator coefficients in descending powers.")
    lsim.add_argument("--input", choices=["ramp", "sine", "square"], default="ramp")
    lsim.add_argument("--tfinal", type=float, default=10.0)
    lsim.add_argument("--dt", type=float, default=0.01)
    lsim.add_argument("--plot", action="store_true", help="Show and save plot.")

    step = sub.add_parser(
        "step-ss",
        parents=[common],
        help="MIMO state-space step response from a selected input",
    )
    step.add_argument("--A", type=str, default="-1 -1; 6.5 0")
    step.add_argument("--B", type=str, default="1 1; 1 0")
    step.add_argument("--C", type=str, default="1 0; 0 1")
    step.add_argument("--D", type=str, default="0 0; 0 0")
    step.add_argument("--input-index", type=int, default=0, help="Zero-based input channel index.")
    step.add_argument("--tfinal", type=float, default=10.0)
    step.add_argument("--dt", type=float, default=0.01)
    step.add_argument("--plot", action="store_true", help="Show and save plots.")
    step.add_argument("--states", action="store_true", help="Also export states through forced response.")
    step.add_argument("--metrics", action="store_true", help="Export basic step metrics.")
    step.add_argument("--save-prefix", type=str, default="ex5_3_from_u", help="Filename prefix for step outputs.")
    step.add_argument("--states-name", type=str, default="ex5_3_states_u", help="Filename prefix for state outputs.")

    second = sub.add_parser(
        "second-order",
        parents=[common],
        help="standard second-order response, single case or damping sweep",
    )
    second.add_argument("--wn", type=float, default=None, help="Natural frequency in rad/s.")
    second.add_argument("--zeta", type=float, default=None, help="Damping ratio.")
    second.add_argument("--K", type=float, default=None, help="Numerator gain. Default uses wn squared.")
    second.add_argument(
        "--coeffs",
        type=float,
        nargs=4,
        metavar=("K", "a2", "a1", "a0"),
        help="Alternative coefficient tuple.",
    )
    second.add_argument("--tfinal", type=float, default=None, help="Time horizon. Auto if omitted.")
    second.add_argument("--dt", type=float, default=1e-3, help="Sample step for plotting.")
    second.add_argument("--sweep-zeta", type=str, default="", help="Comma-separated damping-ratio sweep.")
    second.add_argument("--plot", action="store_true", help="Show and save plots.")
    second.add_argument("--save-prefix", type=str, default="second_order", help="Filename prefix for outputs.")

    overlays = sub.add_parser(
        "second-order-overlays",
        parents=[common],
        help="2D overlays for selected damping-ratio values",
    )
    overlays.add_argument("--wn", type=float, default=1.0, help="Natural frequency in rad/s.")
    overlays.add_argument("--zetas", type=str, default=None, help="Damping-ratio list.")
    overlays.add_argument("--tfinal", type=float, default=10.0, help="Simulation final time.")
    overlays.add_argument("--dt", type=float, default=0.01, help="Time step.")
    overlays.add_argument("--save-prefix", type=str, default="std2_overlays", help="Filename prefix for outputs.")
    overlays.add_argument("--plot", action="store_true", help="Show and save plot.")

    mesh = sub.add_parser(
        "second-order-mesh",
        parents=[common],
        help="3D response surface over time and damping ratio",
    )
    mesh.add_argument("--wn", type=float, default=1.0, help="Natural frequency in rad/s.")
    mesh.add_argument("--zeta-min", type=float, default=0.0, help="Minimum damping ratio.")
    mesh.add_argument("--zeta-max", type=float, default=1.0, help="Maximum damping ratio.")
    mesh.add_argument("--zeta-steps", type=int, default=41, help="Number of damping-ratio samples.")
    mesh.add_argument("--tfinal", type=float, default=10.0, help="Simulation final time.")
    mesh.add_argument("--dt", type=float, default=0.01, help="Time step.")
    mesh.add_argument("--save-prefix", type=str, default="std2_surface", help="Filename prefix for outputs.")
    mesh.add_argument("--no-heatmap", action="store_true", help="Do not render the heatmap image.")
    mesh.add_argument("--plotly", action="store_true", help="Attempt interactive Plotly surface.")
    mesh.add_argument("--plot", action="store_true", help="Render and save the 3D wireframe.")

    plotly = sub.add_parser(
        "second-order-plotly",
        parents=[common],
        help="interactive Plotly 3D surface for a standard second-order system",
    )
    plotly.add_argument("--wn", type=float, default=1.0, help="Natural frequency in rad/s.")
    plotly.add_argument("--zeta-min", type=float, default=0.0, help="Minimum damping ratio.")
    plotly.add_argument("--zeta-max", type=float, default=1.0, help="Maximum damping ratio.")
    plotly.add_argument("--zeta-steps", type=int, default=51, help="Number of damping-ratio samples.")
    plotly.add_argument("--tfinal", type=float, default=10.0, help="Simulation horizon in seconds.")
    plotly.add_argument("--dt", type=float, default=0.01, help="Time step in seconds.")
    plotly.add_argument("--overlay", type=str, default="", help="Damping-ratio values to overlay as 3D line slices.")
    plotly.add_argument("--title", type=str, default="", help="Custom title suffix.")
    plotly.add_argument("--save-prefix", type=str, default="plotly_surface", help="Filename prefix for JSON snapshot.")
    plotly.add_argument("--save-html", type=str, default="", help="Relative HTML filename under the output directory.")
    plotly.add_argument("--save-png", type=str, default="", help="Relative PNG filename under the output directory.")

    return parser


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the responseTool command-line interface."""
    args = build_parser().parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    root_arg = getattr(args, "root", None)
    app = ResponseToolApp(
        root=(Path(root_arg) if root_arg else None),
        show_plots=bool(getattr(args, "plot", False)),
    )

    if args.cmd == "ramp-ss":
        A = parse_matrix(args.A)
        B = parse_matrix(args.B)
        C = parse_matrix(args.C)
        D = parse_matrix(args.D)
        if D is None:
            D = np.zeros((C.shape[0], B.shape[1]))
        app.compute_unit_ramp_ss(
            A,
            B,
            C,
            D,
            tfinal=args.tfinal,
            dt=args.dt,
            title_suffix="  (Ogata Section 5-5)",
        )
        return 0

    if args.cmd == "lsim-tf":
        num = parse_vector(args.num)
        den = parse_vector(args.den)
        app.simulate_tf_input(
            num,
            den,
            u=args.input,
            tfinal=args.tfinal,
            dt=args.dt,
            title=f"Arbitrary input for transfer function: {args.input}",
        )
        return 0

    if args.cmd == "step-ss":
        A = parse_matrix(args.A)
        B = parse_matrix(args.B)
        C = parse_matrix(args.C)
        D = parse_matrix(args.D)
        app.step_ss_from_input(
            A,
            B,
            C,
            D,
            input_index=args.input_index,
            tfinal=args.tfinal,
            dt=args.dt,
            title=f"Step from input u{args.input_index + 1}",
            save_prefix=args.save_prefix,
        )
        if args.states:
            app.step_ss_states(
                A,
                B,
                C,
                D,
                input_index=args.input_index,
                tfinal=args.tfinal,
                dt=args.dt,
                save_name=args.states_name,
            )
        if args.metrics:
            app.ss_step_metrics(A, B, C, D)
        return 0

    if args.cmd == "second-order":
        if args.sweep_zeta.strip():
            zetas = [float(z) for z in args.sweep_zeta.split(",")]
            app.second_order_sweep(
                wn=float(args.wn if args.wn is not None else 5.0),
                zetas=zetas,
                tfinal=args.tfinal,
                dt=args.dt,
                save_prefix=args.save_prefix,
            )
            return 0

        coeffs = tuple(args.coeffs) if args.coeffs is not None else None
        app.second_order_single(
            wn=(None if coeffs else float(args.wn) if args.wn is not None else None),
            zeta=(None if coeffs else float(args.zeta) if args.zeta is not None else None),
            K=(None if coeffs else (None if args.K is None else float(args.K))),
            coeffs=coeffs,
            tfinal=args.tfinal,
            dt=args.dt,
            save_prefix=args.save_prefix,
        )
        return 0

    if args.cmd == "second-order-overlays":
        zetas = parse_zetas_list(getattr(args, "zetas", None))
        app.second_order_overlays(
            wn=float(args.wn),
            zetas=zetas,
            tfinal=float(args.tfinal),
            dt=float(args.dt),
            save_prefix=str(args.save_prefix),
            title_suffix="",
        )
        return 0

    if args.cmd == "second-order-mesh":
        app.second_order_mesh(
            wn=float(args.wn),
            zeta_min=float(args.zeta_min),
            zeta_max=float(args.zeta_max),
            zeta_steps=int(args.zeta_steps),
            tfinal=float(args.tfinal),
            dt=float(args.dt),
            save_prefix=str(args.save_prefix),
            title_suffix="",
            plot_heatmap=(not bool(getattr(args, "no_heatmap", False))),
            plotly=bool(getattr(args, "plotly", False)),
        )
        return 0

    if args.cmd == "second-order-plotly":
        overlay = parse_overlay_list(getattr(args, "overlay", None))
        save_html = getattr(args, "save_html", "") or None
        save_png = getattr(args, "save_png", "") or None
        app.second_order_plotly_surface(
            wn=float(args.wn),
            zeta_min=float(args.zeta_min),
            zeta_max=float(args.zeta_max),
            zeta_steps=int(args.zeta_steps),
            tfinal=float(args.tfinal),
            dt=float(args.dt),
            overlay=overlay,
            title=str(getattr(args, "title", "") or ""),
            save_prefix=str(args.save_prefix),
            save_html=save_html,
            save_png=save_png,
        )
        return 0

    return 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
