#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ---------------------------------
# File: transient_analysis/icTool/cli.py
# ---------------------------------
from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

import click

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root two levels up to sys.path.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from transient_analysis.icTool.app import IcToolApp
    from transient_analysis.icTool.utils import parse_matrix, parse_vector, time_grid, parse_poly
else:
    from .app import IcToolApp
    from .utils import parse_matrix, parse_vector, time_grid, parse_poly


_PACKAGE = "transient_analysis.icTool"
_PROJECT = "modernControl - transient_analysis.icTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "transient_analysis.icTool.cli",
    "transient_analysis.icTool.app",
    "transient_analysis.icTool.utils",
]
_OPTIONAL_MODULES = [
    "transient_analysis.icTool.apis",
    "transient_analysis.icTool.core",
    "transient_analysis.icTool.design",
    "transient_analysis.icTool.io",
    "transient_analysis.icTool.plotting",
]


def _available_modules() -> list[str]:
    """Return only modules that can be imported by Sphinx autodoc."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write a text file unless it already exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> icTool -> transient_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


@click.group(help="icTool - response to initial conditions by direct and step-equivalent methods.")
def cli() -> None:
    """Command line interface for initial-condition response analysis."""
    pass


# =========================
# Sphinx skeleton command
# =========================


@cli.command("sphinx-skel", help="Create a deploy-safe Sphinx documentation skeleton for this package.")
@click.argument("dest", type=click.Path(file_okay=False, dir_okay=True, path_type=Path))
@click.option("--force", is_flag=True, help="Overwrite existing Sphinx skeleton files.")
def cmd_sphinx_skel(dest: Path, force: bool) -> None:
    """Generate Sphinx files with safe headings and tracked support folders."""
    written = _write_sphinx_skeleton(dest, force=force)
    click.echo(f"Sphinx skeleton ready: {dest}")
    if written:
        click.echo("Written files:")
        for path in written:
            click.echo(f"  {path}")
    else:
        click.echo("No existing files were overwritten. Use --force to regenerate.")
    click.echo("Support files ensured:")
    click.echo(f"  {dest / '_static' / '.gitkeep'}")
    click.echo(f"  {dest / '_templates' / '.gitkeep'}")


# =========================
# State-space oriented cmds
# =========================


@cli.command("compare1", help="Case 1: states - compare direct vs step-equivalent")
@click.option("--A", "A_s", required=True, type=str, help="A matrix, for example '0 1; -6 -5'.")
@click.option("--x0", "x0_s", required=True, type=str, help="Initial state vector, for example '2; 1'.")
@click.option("--tfinal", default=3.0, show_default=True, type=float)
@click.option("--dt", default=0.005, show_default=True, type=float)
@click.option("--save/--no-save", default=False, show_default=True, help="Save plot to out.")
@click.option(
    "--base",
    default=None,
    type=click.Path(file_okay=False, dir_okay=True),
    help="Base directory for input and output folders. Default is the package directory.",
)
def cmd_compare1(A_s: str, x0_s: str, tfinal: float, dt: float, save: bool, base: str | None) -> None:
    """Compare direct and step-equivalent state responses."""
    app = IcToolApp(Path(base) if base else None)
    A = parse_matrix(A_s)
    x0 = parse_vector(x0_s)
    T = time_grid(tfinal, dt)
    _ = app.run_compare1(A, x0, T, save=save)
    click.echo("Compare1 OK - direct and step-equivalent computed.")


@cli.command("compare2", help="Case 2: outputs - compare direct vs step-equivalent")
@click.option("--A", "A_s", required=True, type=str, help="A matrix, for example '0 1 0; 0 0 1; -10 -17 -8'.")
@click.option("--C", "C_s", required=True, type=str, help="C matrix, for example '1 0 0'.")
@click.option("--x0", "x0_s", required=True, type=str, help="Initial state vector, for example '2; 1; 0.5'.")
@click.option("--tfinal", default=10.0, show_default=True, type=float)
@click.option("--dt", default=0.01, show_default=True, type=float)
@click.option("--save/--no-save", default=False, show_default=True)
@click.option("--base", default=None, type=click.Path(file_okay=False, dir_okay=True))
def cmd_compare2(A_s: str, C_s: str, x0_s: str, tfinal: float, dt: float, save: bool, base: str | None) -> None:
    """Compare direct and step-equivalent output responses."""
    app = IcToolApp(Path(base) if base else None)
    A = parse_matrix(A_s)
    C = parse_matrix(C_s)
    x0 = parse_vector(x0_s)
    T = time_grid(tfinal, dt)
    _ = app.run_compare2(A, C, x0, T, save=save)
    click.echo("Compare2 OK - direct and step-equivalent computed.")


@cli.command("case1", help="Case 1: states - direct only")
@click.option("--A", "A_s", required=True, type=str)
@click.option("--x0", "x0_s", required=True, type=str)
@click.option("--tfinal", default=3.0, show_default=True, type=float)
@click.option("--dt", default=0.005, show_default=True, type=float)
@click.option("--save/--no-save", default=False, show_default=True)
@click.option("--base", default=None, type=click.Path(file_okay=False, dir_okay=True))
def cmd_case1(A_s: str, x0_s: str, tfinal: float, dt: float, save: bool, base: str | None) -> None:
    """Compute direct state response from initial conditions."""
    app = IcToolApp(Path(base) if base else None)
    A = parse_matrix(A_s)
    x0 = parse_vector(x0_s)
    T = time_grid(tfinal, dt)
    _ = app.run_case1(A, x0, T, save=save)
    click.echo("Case1 OK - direct IC states computed.")


@cli.command("case2", help="Case 2: outputs - direct only")
@click.option("--A", "A_s", required=True, type=str)
@click.option("--C", "C_s", required=True, type=str)
@click.option("--x0", "x0_s", required=True, type=str)
@click.option("--tfinal", default=3.0, show_default=True, type=float)
@click.option("--dt", default=0.005, show_default=True, type=float)
@click.option("--save/--no-save", default=False, show_default=True)
@click.option("--base", default=None, type=click.Path(file_okay=False, dir_okay=True))
def cmd_case2(A_s: str, C_s: str, x0_s: str, tfinal: float, dt: float, save: bool, base: str | None) -> None:
    """Compute direct output response from initial conditions."""
    app = IcToolApp(Path(base) if base else None)
    A = parse_matrix(A_s)
    C = parse_matrix(C_s)
    x0 = parse_vector(x0_s)
    T = time_grid(tfinal, dt)
    _ = app.run_case2(A, C, x0, T, save=save)
    click.echo("Case2 OK - direct IC outputs computed.")


# =========================
# Transfer-function cmds
# =========================


@cli.command(
    "tf-step-ogata",
    help="TF step-equivalent output via Ogata Example 5-8 parameters.",
)
@click.option("--m", type=float, required=True, help="Mass m.")
@click.option("--b", type=float, required=True, help="Damping b.")
@click.option("--k", type=float, required=True, help="Stiffness k.")
@click.option("--x0", type=float, required=True, help="Initial displacement.")
@click.option("--v0", type=float, required=True, help="Initial velocity.")
@click.option("--tfinal", default=5.0, show_default=True, type=float)
@click.option("--dt", default=0.01, show_default=True, type=float)
@click.option("--save/--no-save", default=False, show_default=True, help="Save plot to out.")
@click.option("--json/--no-json", "save_json", default=False, show_default=True, help="Save series to JSON in out.")
@click.option("--analytic/--no-analytic", default=False, show_default=True, help="Overlay analytic solution when available.")
@click.option(
    "--base",
    default=None,
    type=click.Path(file_okay=False, dir_okay=True),
    help="Base directory for input and output folders. Default is the package directory.",
)
def cmd_tf_step_ogata(
    m: float,
    b: float,
    k: float,
    x0: float,
    v0: float,
    tfinal: float,
    dt: float,
    save: bool,
    save_json: bool,
    analytic: bool,
    base: str | None,
) -> None:
    """Compute a transfer-function step-equivalent response for the Ogata example."""
    app = IcToolApp(Path(base) if base else None)
    T = time_grid(tfinal, dt)
    app.run_tf_step_ogata(m, b, k, x0, v0, T, save=save, save_json=save_json, overlay_analytic=analytic)
    click.echo("TF step Ogata OK - computed and handled outputs.")


@cli.command(
    "tf-step",
    help="TF step-equivalent output from explicit numerator and denominator.",
)
@click.option("--num_ic", type=str, required=True, help="Numerator coefficients for the initial-condition transfer function.")
@click.option("--den", type=str, required=True, help="Denominator coefficients.")
@click.option("--tfinal", default=5.0, show_default=True, type=float)
@click.option("--dt", default=0.01, show_default=True, type=float)
@click.option("--save/--no-save", default=False, show_default=True, help="Save plot to out.")
@click.option("--json/--no-json", "save_json", default=False, show_default=True, help="Save series to JSON in out.")
@click.option(
    "--base",
    default=None,
    type=click.Path(file_okay=False, dir_okay=True),
    help="Base directory for input and output folders. Default is the package directory.",
)
def cmd_tf_step(num_ic: str, den: str, tfinal: float, dt: float, save: bool, save_json: bool, base: str | None) -> None:
    """Compute a generic transfer-function step-equivalent response."""
    app = IcToolApp(Path(base) if base else None)
    T = time_grid(tfinal, dt)
    ni = parse_poly(num_ic)
    dd = parse_poly(den)
    app.run_tf_step_generic(ni, dd, T, save=save, save_json=save_json)
    click.echo("TF step generic OK - computed and handled outputs.")


if __name__ == "__main__":  # pragma: no cover
    cli()
