# Generated by modelingSystems.converterTool.cli
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
project = 'modernControl – modelingSystems.converterTool'
extensions = ['sphinx.ext.autodoc','sphinx.ext.napoleon','sphinx.ext.viewcode']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'furo'
