# Generated by pid_controllers.rootLocusTool.cli
import sys
from pathlib import Path
# docs -> rootLocusTool -> pid_controllers -> <repo root>
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = 'digital-control - pid_controllers.rootLocusTool'
author = 'digital-control'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'furo'
html_static_path = ['_static']

autodoc_typehints = 'description'
napoleon_google_docstring = True
napoleon_numpy_docstring = True
