from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_analysis/stateRepTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_analysis.stateRepTool.apis import StateRepAPIRequest
    from state_space_analysis.stateRepTool.app import StateRepApp
else:
    from .apis import StateRepAPIRequest
    from .app import StateRepApp


_PACKAGE = "state_space_analysis.stateRepTool"
_PROJECT = "modernControl - state_space_analysis.stateRepTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_analysis.stateRepTool.cli",
    "state_space_analysis.stateRepTool.apis",
    "state_space_analysis.stateRepTool.app",
    "state_space_analysis.stateRepTool.core",
    "state_space_analysis.stateRepTool.design",
    "state_space_analysis.stateRepTool.io",
    "state_space_analysis.stateRepTool.utils",
]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> stateRepTool -> state_space_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return '''# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
'''


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="stateRepTool - State-space canonical forms: controllable, observable, diagonal, and Jordan."
    )
    sub = parser.add_subparsers(dest="cmd")

    g_in = parser.add_argument_group("Input")
    g_in.add_argument("--tf", type=str, help='Rational expression in s, for example "(s+3)/(s^2+3*s+2)".')
    g_in.add_argument("--num", type=str, help='Numerator as CSV "1,3" or polynomial "s+3".')
    g_in.add_argument("--den", type=str, help='Denominator as CSV "1,3,2" or polynomial "s^2+3*s+2".')
    g_in.add_argument("--example", type=str, choices=["ogata_9_1"], help="Prefill a known example.")

    g_out = parser.add_argument_group("Options")
    g_out.add_argument(
        "--canonical",
        type=str,
        default="all",
        choices=["all", "controllable", "observable", "diagonal", "jordan"],
    )
    g_out.add_argument("--numeric", action="store_true", help="Print numeric matrix values.")
    g_out.add_argument("--digits", type=int, default=6, help="Digits for numeric print.")
    g_out.add_argument("--no-verify", action="store_true", help="Skip symbolic verification.")
    g_out.add_argument("--pretty", action="store_true", help="Reserved pretty-print option. JSON stores exact values.")
    g_out.add_argument("--export-json", type=str, help="Write results to a JSON file relative to out.")
    g_out.add_argument("--log", type=str, default="INFO", help="Logging level: DEBUG, INFO, WARNING, or ERROR.")

    skel = sub.add_parser("sphinx-skel", help="Create a deploy-safe Sphinx documentation skeleton for this package.")
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_sphinx_skel(dest: Path, *, force: bool = False) -> int:
    written = _write_sphinx_skeleton(dest, force=force)
    print(f"Sphinx skeleton ready: {dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {dest / '_static' / '.gitkeep'}")
    print(f"  {dest / '_templates' / '.gitkeep'}")
    return 0


def _run_state_rep(args: argparse.Namespace) -> int:
    logging.basicConfig(
        level=getattr(logging, str(args.log).upper(), logging.INFO),
        format="%(levelname)s: %(message)s",
    )

    req = StateRepAPIRequest(
        tf=args.tf,
        num=args.num,
        den=args.den,
        example=args.example,
        which=args.canonical,
        numeric=args.numeric,
        digits=args.digits,
        pretty=args.pretty,
        verify=not args.no_verify,
    )
    app = StateRepApp()
    results = app.run(req, export_json=args.export_json)

    for name, blk in results.items():
        print(f"\n== {name.upper()} ==")
        for key in ("A", "B", "C", "D"):
            print(f"{key} = {blk[key]}")

    return 0


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)

    if getattr(args, "cmd", None) == "sphinx-skel":
        raise SystemExit(_run_sphinx_skel(args.dest, force=args.force))

    raise SystemExit(_run_state_rep(args))


if __name__ == "__main__":
    main()
