# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# --- Import shim so `python cli.py` works with absolute imports ---
_SCRIPT_MODE = False
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/gainMatrixTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from state_space_design.gainMatrixTool.app import GainMatrixApp
    _SCRIPT_MODE = True
else:
    from .app import GainMatrixApp


_PACKAGE = "state_space_design.gainMatrixTool"
_PROJECT = "modernControl - state_space_design.gainMatrixTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_design.gainMatrixTool.cli",
    "state_space_design.gainMatrixTool.app",
]


# Add optional modules only when they actually exist. This avoids generating
# Sphinx autodoc entries for ghost modules that would fail deployment.
def _module_exists(module_name: str) -> bool:
    try:
        import importlib.util
        return importlib.util.find_spec(module_name) is not None
    except Exception:
        return False


for _candidate in (
    "state_space_design.gainMatrixTool.apis",
    "state_space_design.gainMatrixTool.core",
    "state_space_design.gainMatrixTool.design",
    "state_space_design.gainMatrixTool.io",
    "state_space_design.gainMatrixTool.utils",
):
    if _module_exists(_candidate):
        _MODULES.append(_candidate)


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> gainMatrixTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _normalize_negative_list_args(argv: list[str] | None) -> list[str] | None:
    """Normalize negative pole-list values so argparse does not treat them as options."""
    if argv is None:
        return None

    out: list[str] = []
    i = 0
    sensitive = {"--poles"}

    while i < len(argv):
        tok = argv[i]

        if tok in sensitive and i + 1 < len(argv):
            j = i + 1
            negs: list[str] = []
            while j < len(argv):
                nxt = argv[j]
                if nxt.startswith("--"):
                    break
                if nxt.startswith("-"):
                    negs.append(nxt)
                    j += 1
                    continue
                break

            if negs:
                out.append(f"{tok}=" + " ".join(negs))
                i = j
                continue

        out.append(tok)
        i += 1

    return out


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="state_space_design.gainMatrixTool",
        description="Gain-matrix design for state feedback, observer gain, and servo integral gain.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd", required=False)

    run = sub.add_parser("run", help="Single-case design")
    run.add_argument("--mode", choices=["K", "L", "KI"], default="K")
    run.add_argument("--A", required=True, help='Matrix A, for example "0 1; -2 -3"')
    run.add_argument("--B", help='Matrix B, for example "0; 1". Required for K and KI modes.')
    run.add_argument("--C", help='Matrix C, for example "1 0". Required for L and KI modes.')
    run.add_argument("--poles", nargs="+", required=True, help='Desired poles, for example "-2+4j -2-4j -10"')
    run.add_argument("--method", choices=["auto", "acker", "place"], default="auto")
    run.add_argument("--verify", action="store_true")
    run.add_argument("--pretty", action="store_true")
    run.add_argument("--export_json", help="Write JSON to path")
    run.add_argument("--log", help="Log file path")
    run.add_argument("--verbose", action="store_true")

    batch = sub.add_parser("batch", help="Batch design from CSV or YAML")
    batch.add_argument("--csv", help="CSV file of cases")
    batch.add_argument("--yaml", help="YAML file of cases")
    default_export = "out_json" if _SCRIPT_MODE else "state_space_design/gainMatrixTool/out_json"
    batch.add_argument("--export_dir", default=default_export, help="Output directory for JSON files")
    batch.add_argument("--verify", action="store_true")
    batch.add_argument("--pretty", action="store_true")
    batch.add_argument("--log", help="Log file path")
    batch.add_argument("--verbose", action="store_true")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def _run_design(args: argparse.Namespace) -> int:
    app = GainMatrixApp.default()
    app.configure_logging(getattr(args, "log", None), getattr(args, "verbose", False))

    if args.cmd == "run":
        if args.mode in ("K", "KI") and not args.B:
            raise SystemExit("--B required for mode K/KI")
        if args.mode in ("L", "KI") and not args.C:
            raise SystemExit("--C required for mode L/KI")

        payload = app.run_single(
            mode=args.mode,
            A=args.A,
            B=args.B,
            C=args.C,
            poles=args.poles,
            method=args.method,
            verify=args.verify,
            pretty=args.pretty,
        )
        if args.export_json:
            if __package__ in (None, ""):
                from state_space_design.gainMatrixTool.io import JsonExporter
            else:
                from .io import JsonExporter
            JsonExporter().export(payload, args.export_json)
        return 0

    if args.cmd == "batch":
        if not args.csv and not args.yaml:
            raise SystemExit("Provide --csv or --yaml")
        app.run_batch(args.csv, args.yaml, args.export_dir, args.verify, args.pretty)
        return 0

    return 0


def main(argv: list[str] | None = None) -> int:
    argv = _normalize_negative_list_args(list(argv) if argv is not None else sys.argv[1:])
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd in {"run", "batch"}:
        return _run_design(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
