# SPDX-License-Identifier: MIT
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path

# --------------------------------------------------------------
# Import shim so `python cli.py` works from inside the folder.
# --------------------------------------------------------------
if __package__ in (None, ""):
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.statePlotsTool.app import StatePlotsApp, main_kwargs_from_args
    from state_space_design.statePlotsTool.apis import StatePlotsAPI

    RUN_LOCAL = True
    BASE_DIR = os.path.dirname(__file__)
    IN_DIR = os.path.join(BASE_DIR, "in")
    OUT_DIR = os.path.join(BASE_DIR, "out")
else:
    from .app import StatePlotsApp, main_kwargs_from_args
    from .apis import StatePlotsAPI

    RUN_LOCAL = False
    BASE_DIR = os.path.dirname(__file__)
    IN_DIR = os.path.join(BASE_DIR, "in")
    OUT_DIR = os.path.join(BASE_DIR, "out")


_PACKAGE = "state_space_design.statePlotsTool"
_PROJECT = "modernControl - state_space_design.statePlotsTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "state_space_design.statePlotsTool.cli",
    "state_space_design.statePlotsTool.apis",
    "state_space_design.statePlotsTool.app",
]
_OPTIONAL_MODULES = [
    "state_space_design.statePlotsTool.core",
    "state_space_design.statePlotsTool.design",
    "state_space_design.statePlotsTool.io",
    "state_space_design.statePlotsTool.plotting",
    "state_space_design.statePlotsTool.utils",
]


def _module_exists(module_name: str) -> bool:
    """Return true when a module can be located without importing it."""
    try:
        return importlib.util.find_spec(module_name) is not None
    except Exception:
        return False


def _documented_modules() -> list[str]:
    """Return the importable modules that should appear in the API page."""
    modules = list(_REQUIRED_MODULES)
    modules.extend(mod for mod in _OPTIONAL_MODULES if _module_exists(mod))
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text unless the file already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and gitkeep files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> statePlotsTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with safe heading formatting."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that only references real modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _documented_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _normalize_data_path(data: str) -> str:
    """Resolve a bare data filename to the local input folder in script mode."""
    if os.path.isabs(data):
        return data
    if RUN_LOCAL:
        return os.path.join(IN_DIR, data) if not os.path.dirname(data) else data
    return data


def _ensure_out_path(name: str | None) -> str | None:
    """Place bare output filenames under the package output folder."""
    if not name:
        return None
    if os.path.dirname(name):
        os.makedirs(os.path.dirname(name), exist_ok=True)
        return name
    os.makedirs(OUT_DIR, exist_ok=True)
    return os.path.join(OUT_DIR, name)


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    ap.add_argument("--data", required=True, help="JSON filename. In script mode, bare filenames are read from the local input folder.")
    ap.add_argument("--scenario", choices=["auto", "ic", "step"], default="auto", help="Detect or force the scenario.")
    ap.add_argument("--what", choices=["auto", "y", "states", "both"], default="auto", help="What to plot for step cases. Initial-condition cases always plot states.")
    ap.add_argument("--subplots", action="store_true", help="Use stacked subplots instead of overlay plots.")
    ap.add_argument("--x0", default=None, help='Initial-condition vector, for example "1 0 0".')
    ap.add_argument("--t", default="0:0.01:4", help='Time vector, for example "0:0.01:4" or an explicit list.')
    ap.add_argument("--backend", choices=["mpl", "plotly", "both", "none"], default="both", help="Plotting backend.")
    ap.add_argument("--save_png", default=None, help="PNG filename. Bare names are written under the local output folder.")
    ap.add_argument("--save_html", default=None, help="Plotly HTML filename. Bare names are written under the local output folder.")
    ap.add_argument("--save_csv", default=None, help="CSV filename. Bare names are written under the local output folder.")
    ap.add_argument("--no_show", action="store_true", help="Do not display GUI windows.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="state_space_design.statePlotsTool",
        description="State-space plots for initial-condition and step scenarios from controller or I/O JSON.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="generate state-space plots and optional CSV export",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_state_plots(args: argparse.Namespace) -> int:
    args.data = _normalize_data_path(args.data)
    args.save_png = _ensure_out_path(args.save_png)
    args.save_html = _ensure_out_path(args.save_html)
    args.save_csv = _ensure_out_path(args.save_csv)

    app = StatePlotsApp(api=StatePlotsAPI())
    kwargs = main_kwargs_from_args(args)
    result = app.run(**kwargs)

    print("Scenario:", result["scenario"])
    if result.get("paths"):
        for key, value in result["paths"].items():
            if value:
                print(f"Wrote {key}:", value)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    raw = list(argv) if argv is not None else list(sys.argv[1:])

    # Preserve the original no-subcommand usage, for example:
    # python cli.py --data run.json --backend both
    if raw and raw[0] not in {"run", "sphinx-skel", "-h", "--help"}:
        raw = ["run", *raw]

    args = parser.parse_args(raw)

    if args.cmd == "run":
        return _run_state_plots(args)
    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
