# Generated by frequency_response.experimentTool.cli
import sys
from pathlib import Path
# docs -> experimentTool -> frequency_response -> <repo root>
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
project = 'modernControl – frequency_response.experimentTool'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'furo'
autodoc_typehints = 'description'
