# =============================
# File: transient_analysis/hurwitzTool/cli.py
# =============================
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path

import numpy as np
import sympy as sp

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from transient_analysis.hurwitzTool.apis import (
        HurwitzService,
        NumericCheckRequest,
        SymbolicRegionRequest,
        Scan1DRequest,
        Scan2DRequest,
    )
    from transient_analysis.hurwitzTool.utils import ascii_heatmap, parse_coeffs
    from transient_analysis.hurwitzTool.io import IOManager
else:
    from .apis import (
        HurwitzService,
        NumericCheckRequest,
        SymbolicRegionRequest,
        Scan1DRequest,
        Scan2DRequest,
    )
    from .utils import ascii_heatmap, parse_coeffs
    from .io import IOManager


_PACKAGE = "transient_analysis.hurwitzTool"
_PROJECT = "modernControl - transient_analysis.hurwitzTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "transient_analysis.hurwitzTool.cli",
    "transient_analysis.hurwitzTool.apis",
    "transient_analysis.hurwitzTool.utils",
    "transient_analysis.hurwitzTool.io",
]
_OPTIONAL_MODULES = [
    "transient_analysis.hurwitzTool.app",
    "transient_analysis.hurwitzTool.core",
    "transient_analysis.hurwitzTool.design",
    "transient_analysis.hurwitzTool.plotting",
]


def _available_modules() -> list[str]:
    """Return only modules that Python can import."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text unless the file already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> hurwitzTool -> transient_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx index page with safe heading lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build an API page that documents only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add the original Hurwitz analysis arguments to a parser."""
    ap.add_argument(
        "--coeffs",
        required=True,
        help="Descending polynomial coefficients. Symbols are allowed.",
    )
    ap.add_argument(
        "--symbols",
        default=None,
        help="Comma-separated symbol names. If omitted, symbols are detected automatically.",
    )
    ap.add_argument(
        "--solve-for",
        dest="solvefor",
        default=None,
        help="Solve the stability region for these symbols.",
    )
    ap.add_argument(
        "--lienard",
        action="store_true",
        help="Use the Lienard-Chipart reduced tests with positive coefficient checks.",
    )
    ap.add_argument(
        "--subs",
        default=None,
        help="Numeric substitutions such as K=3.5,alpha=2.",
    )
    ap.add_argument(
        "--verify",
        action="store_true",
        help="Count right-half-plane roots with numpy.roots after substitution.",
    )
    ap.add_argument("--scan", default=None, help="One-dimensional scan formatted as K:lo:hi:step.")
    ap.add_argument("--scan2", default=None, help="Two-dimensional scan formatted as S1:lo:hi:ds;S2:lo:hi:ds.")
    ap.add_argument("--csv", default=None, help="CSV path for one-dimensional scan results.")
    ap.add_argument("--csv2", default=None, help="CSV path for two-dimensional scan results.")
    ap.add_argument("--png", default=None, help="PNG heatmap path for two-dimensional scan results.")
    ap.add_argument("--tol", type=float, default=1e-10, help="Numerical tolerance.")
    ap.add_argument(
        "--intervals-pretty",
        action="store_true",
        help="Print simplified interval and LaTeX text for one-dimensional symbolic regions.",
    )
    ap.add_argument(
        "--base-dir",
        default=".",
        help="Base directory for hurwitzTool input and output folders.",
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        description="Hurwitz stability tool with numeric checks, symbolic regions, and scans.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run Hurwitz stability analysis",
        description="Run numeric, symbolic, one-dimensional, or two-dimensional Hurwitz analysis.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _parse_subs_arg(s: str | None) -> dict[str, float]:
    """Parse numeric substitutions from a comma-separated string."""
    if not s:
        return {}
    out: dict[str, float] = {}
    for part in s.replace(";", ",").split(","):
        if not part.strip():
            continue
        if "=" not in part:
            raise ValueError(f"Bad --subs item {part!r}; expected NAME=value.")
        key, value = part.split("=", 1)
        out[key.strip()] = float(value.strip())
    return out


def _parse_scan1d_arg(scan: str) -> tuple[str, float, float, float]:
    """Parse a one-dimensional scan specification."""
    name, lo, hi, step = [q.strip() for q in scan.replace(";", ":").split(":")]
    return name, float(lo), float(hi), float(step)


def _parse_scan2d_arg(scan2: str) -> tuple[tuple[str, float, float, float], tuple[str, float, float, float]]:
    """Parse a two-dimensional scan specification."""
    parts = [p.strip() for p in scan2.split(";") if p.strip()]
    if len(parts) != 2:
        raise ValueError("Bad --scan2 value. Expected S1:lo:hi:ds;S2:lo:hi:ds.")
    sx, xlo, xhi, dx = [q.strip() for q in parts[0].split(":")]
    sy, ylo, yhi, dy = [q.strip() for q in parts[1].split(":")]
    return (sx, float(xlo), float(xhi), float(dx)), (sy, float(ylo), float(yhi), float(dy))


def _run_scan1d(args: argparse.Namespace, svc: HurwitzService, iom: IOManager) -> None:
    """Run and optionally export a one-dimensional stability scan."""
    name, lo, hi, step = _parse_scan1d_arg(args.scan)
    res1 = svc.scan1d(
        Scan1DRequest(
            coeffs=args.coeffs,
            symbol=name,
            lo=lo,
            hi=hi,
            step=step,
            use_lienard=args.lienard,
        )
    )
    print("\nSampled stability:")
    for t, ok in res1.samples:
        print(f"  {t:.6g}, {ok}")
    if args.csv:
        path = iom.save_csv(
            Path(args.csv),
            ["t", "stable"],
            [[t, int(ok)] for t, ok in res1.samples],
        )
        print(f"Saved CSV -> {path}")


def _run_scan2d(args: argparse.Namespace, svc: HurwitzService, iom: IOManager) -> None:
    """Run and optionally export a two-dimensional stability scan."""
    (sx, xlo, xhi, dx), (sy, ylo, yhi, dy) = _parse_scan2d_arg(args.scan2)
    res2 = svc.scan2d(
        Scan2DRequest(
            coeffs=args.coeffs,
            sx=sx,
            sy=sy,
            xlo=xlo,
            xhi=xhi,
            dx=dx,
            ylo=ylo,
            yhi=yhi,
            dy=dy,
            use_lienard=args.lienard,
        )
    )
    print("\n2-D scan ASCII heatmap. Filled cells are stable.")
    print(
        f"x={sx} in [{res2.xs.min():.6g},{res2.xs.max():.6g}] step {dx},  "
        f"y={sy} in [{res2.ys.min():.6g},{res2.ys.max():.6g}] step {dy}"
    )
    print(ascii_heatmap(res2.xs, res2.ys, res2.Z, invert_y=True))

    if args.csv2:
        X, Y = np.meshgrid(res2.xs, res2.ys)
        rows = [
            [float(X.ravel()[i]), float(Y.ravel()[i]), int(res2.Z.astype(int).ravel()[i])]
            for i in range(X.size)
        ]
        path = iom.save_csv(Path(args.csv2), ["x", "y", "stable"], rows)
        print(f"Saved CSV -> {path}")

    if args.png:
        msg = iom.save_png_heatmap(Path(args.png), res2.xs, res2.ys, res2.Z)
        if msg:
            print(msg)


def _run_hurwitz(args: argparse.Namespace) -> int:
    """Run the Hurwitz analysis workflow."""
    base_dir = Path(args.base_dir).resolve()
    svc = HurwitzService(base_dir)
    iom = IOManager(base_dir)

    if args.subs:
        subs = _parse_subs_arg(args.subs)
        res = svc.numeric_check(
            NumericCheckRequest(
                coeffs=args.coeffs,
                subs=subs,
                use_lienard=args.lienard,
                tol=args.tol,
            )
        )
        print("Used:", res.used)
        print("a (numeric) =", res.a_numeric)
        print("Delta values:")
        for i, d in enumerate(res.minors_numeric, 1):
            print(f"  Delta {i} = {d:.12g}")
        print("\nChecks:")
        print("  a0 > 0?", res.a0_pos)
        if args.lienard:
            print("  all coefficients > 0?", res.coeff_pos)
        print("\nHurwitz stable?", res.ok)

        if args.verify:
            a_num = [
                float(sp.N(ai.subs({sp.Symbol(k): v for k, v in subs.items()})))
                for ai in parse_coeffs(args.coeffs)
            ]
            roots = np.roots(np.array(a_num, dtype=float))
            print(
                "Verification: number of right-half-plane roots by numpy.roots =",
                int(np.sum(np.real(roots) > args.tol)),
            )

        if args.scan:
            _run_scan1d(args, svc, iom)

        return 0

    coeffs = parse_coeffs(args.coeffs)
    if all(ai.is_number for ai in coeffs):
        res = svc.numeric_check(
            NumericCheckRequest(
                coeffs=args.coeffs,
                subs={},
                use_lienard=args.lienard,
                tol=args.tol,
            )
        )
        print("Used:", res.used)
        print("a =", res.a_numeric)
        print("Delta values:")
        for i, d in enumerate(res.minors_numeric, 1):
            print(f"  Delta {i} = {d:.12g}")
        print("\nHurwitz stable?", res.ok)
        return 0

    symres = svc.symbolic_region(
        SymbolicRegionRequest(
            coeffs=args.coeffs,
            symbols=args.symbols,
            solvefor=args.solvefor,
            use_lienard=args.lienard,
            intervals_pretty=args.intervals_pretty,
        )
    )
    print("Variables:", symres.variables)
    print("Used:", symres.used)
    print("Region:", symres.region)
    if symres.pretty:
        print("\nPretty intervals:")
        print("  ", symres.pretty)
        print("LaTeX intervals:")
        print("  ", symres.latex)

    if args.scan and len(symres.variables) == 1:
        _run_scan1d(args, svc, iom)

    if args.scan2 and len(symres.variables) >= 2:
        _run_scan2d(args, svc, iom)

    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the hurwitzTool command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_hurwitz(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
