#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import importlib.util
import logging as log
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/robustTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.robustTool.apis import RunRequest
    from state_space_design.robustTool.app import RobustApp
    from state_space_design.robustTool.io import save_json
else:
    from .apis import RunRequest
    from .app import RobustApp
    from .io import save_json


_PACKAGE = "state_space_design.robustTool"
_PROJECT = "modernControl - state_space_design.robustTool"
_AUTHOR = "modernControl"
_BASE_MODULES = [
    "state_space_design.robustTool.cli",
    "state_space_design.robustTool.apis",
    "state_space_design.robustTool.app",
    "state_space_design.robustTool.io",
]
_OPTIONAL_MODULES = [
    "state_space_design.robustTool.core",
    "state_space_design.robustTool.design",
    "state_space_design.robustTool.plotting",
    "state_space_design.robustTool.utils",
]

# When running from inside robustTool, write artifacts to ./out by default.
OUT_DIR = "out"


def _module_exists(module_name: str) -> bool:
    """Return true when a module can be found without importing it."""
    try:
        return importlib.util.find_spec(module_name) is not None
    except Exception:
        return False


def _documented_modules() -> list[str]:
    """Return only modules that should be safe for Sphinx autodoc."""
    modules = list(_BASE_MODULES)
    for mod in _OPTIONAL_MODULES:
        if _module_exists(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> robustTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _documented_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _normalize_argv(argv: list[str] | None) -> list[str] | None:
    """Normalize option values that begin with a minus sign."""
    if argv is None:
        return None
    expects_value = {
        "--num", "--den",
        "--pid", "--K_num", "--K_den",
        "--Wm_num", "--Wm_den",
        "--Ws_num", "--Ws_den",
        "--Wa_num", "--Wa_den",
        "--export-json",
    }
    out: list[str] = []
    i = 0
    while i < len(argv):
        tok = argv[i]
        if tok in expects_value and (i + 1) < len(argv):
            nxt = argv[i + 1]
            if nxt.startswith("-") and not nxt.replace("-", "").isdigit():
                out.append(f"{tok}={nxt}")
                i += 2
                continue
        out.append(tok)
        i += 1
    return out


def _ensure_prefix_dir(path: str | None) -> str | None:
    """Place bare output filenames under the local out directory."""
    if not path:
        return None
    dname = os.path.dirname(path)
    if not dname:
        os.makedirs(OUT_DIR, exist_ok=True)
        return os.path.join(OUT_DIR, path)
    os.makedirs(dname, exist_ok=True)
    return path


def build_parser() -> argparse.ArgumentParser:
    """Build the command line parser."""
    parser = argparse.ArgumentParser(
        prog="state_space_design.robustTool",
        description="Robust control sweeps for Ogata section 10-9.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run a robust-control sweep",
        description="Run robust-control frequency sweeps and optional step-response analysis.",
    )

    # Plant
    run.add_argument("--num", required=True, help='Plant numerator coefficients, for example "10 20".')
    run.add_argument("--den", required=True, help='Plant denominator coefficients, for example "1 10 24 0".')

    # Controller
    run.add_argument("--pid", default=None, help="PID coefficients as kp,ki,kd,nd.")
    run.add_argument("--K_num", default=None)
    run.add_argument("--K_den", default=None)

    # Weights
    run.add_argument("--Wm_num", default=None)
    run.add_argument("--Wm_den", default=None)
    run.add_argument("--Ws_num", default=None)
    run.add_argument("--Ws_den", default=None)
    run.add_argument("--Wa_num", default=None)
    run.add_argument("--Wa_den", default=None)

    # Sweep grid
    run.add_argument("--wmin", type=float, default=1e-2)
    run.add_argument("--wmax", type=float, default=1e2)
    run.add_argument("--npts", type=int, default=400)

    # Step response
    run.add_argument("--step", action="store_true")
    run.add_argument("--tfinal", type=float, default=8.0)
    run.add_argument("--dt", type=float, default=0.01)

    # Plots and IO
    run.add_argument("--plots", choices=["mpl", "plotly", "both", "none"], default="mpl")
    run.add_argument(
        "--export-json",
        default=None,
        help="JSON output path. Bare filenames are written using the package writer.",
    )
    run.add_argument("--loglevel", choices=["DEBUG", "INFO", "WARNING", "ERROR"], default="INFO")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_robust(args: argparse.Namespace) -> int:
    log.basicConfig(level=getattr(log, args.loglevel), format="%(levelname)s: %(message)s")

    req = RunRequest(**vars(args))
    app = RobustApp()
    res = app.run(req)

    if args.export_json:
        if os.path.dirname(args.export_json):
            directory = os.path.dirname(args.export_json)
            if directory and not os.path.exists(directory):
                os.makedirs(directory, exist_ok=True)
            with open(args.export_json, "w", encoding="utf-8") as f:
                import json
                f.write(json.dumps(res.to_jsonable(), indent=2))
            print(f"Saved JSON -> {args.export_json}")
        else:
            out = save_json(res.to_jsonable(), args.export_json)
            print(f"Saved JSON -> {out}")
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = _normalize_argv(list(argv) if argv is not None else sys.argv[1:])
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility for the historical no-subcommand CLI shape.
    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_robust(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
