
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional, List

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from modeling_control_systems.mimoTool.apis import RunConfig
    from modeling_control_systems.mimoTool.app import MIMOApp
else:
    from .apis import RunConfig
    from .app import MIMOApp

def _level(v: int):
    return logging.DEBUG if v >= 2 else (logging.INFO if v == 1 else logging.INFO)

# -------------------------- Sphinx skeleton helper --------------------------
def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    dest.mkdir(parents=True, exist_ok=True)
    conf = (
        "# Generated by modeling_control_systems.mimoTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n"
        "project = 'modernControl – modeling_control_systems.mimoTool'\n"
        "extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = []\n"
        "html_theme = 'furo'\n"
    )
    index = (
        ".. modeling_control_systems.mimoTool documentation\n\n"
        "Welcome to modeling_control_systems.mimoTool's docs!\n"
        "===========================================\n\n"
        ".. toctree::\n"
        "   :maxdepth: 2\n"
        "   :caption: Contents:\n\n"
        "   api\n"
    )
    api = (
        "API Reference\n"
        "=============\n\n"
        ".. automodule:: modeling_control_systems.mimoTool.app\n"
        "   :members:\n"
        "   :undoc-members:\n\n"
        ".. automodule:: modeling_control_systems.mimoTool.apis\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: modeling_control_systems.mimoTool.core\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: modeling_control_systems.mimoTool.design\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: modeling_control_systems.mimoTool.io\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: modeling_control_systems.mimoTool.utils\n"
        "   :members:\n"
        "   :undoc-members:\n"
    )
    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )
    def _write(path: Path, text: str):
        if path.exists() and not force:
            return
        path.write_text(text, encoding='utf-8')
    (dest / "_templates").mkdir(exist_ok=True)
    (dest / "_static").mkdir(exist_ok=True)
    _write(dest / "conf.py", conf)
    _write(dest / "index.rst", index)
    _write(dest / "api.rst", api)
    _write(dest / "Makefile", makefile)
    return dest

# ------------------------------ CLI parsers --------------------------------
def _build_run_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="MIMO examples: steps per input and σ(G(jω)) plots.")
    ap.add_argument("--plant", action="append", choices=["two_tank", "two_zone_thermal"], required=True,
                    help="Which plant(s) to analyze. May be passed multiple times.")
    ap.add_argument("--tfinal", type=float, default=200.0)
    ap.add_argument("--dt", type=float, default=0.25)
    ap.add_argument("--wmin", type=float, default=1e-3)
    ap.add_argument("--wmax", type=float, default=10**1.5)
    ap.add_argument("--npts", type=int, default=400)
    ap.add_argument("--no-steps", dest="plot_steps", action="store_false")
    ap.add_argument("--no-sigma", dest="plot_sigma", action="store_false")
    ap.add_argument("--no-show", dest="show", action="store_false")
    ap.add_argument("--save-png", help='Template like "modeling_control_systems/mimoTool/out/{plant}_{kind}.png"')
    ap.add_argument("--save-json", help='Template like "modeling_control_systems/mimoTool/out/{plant}_summary.json"')
    ap.add_argument("--title", default="Step")
    ap.add_argument("-v","--verbose", action="count", default=0)
    return ap

def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="sphinx-skel", description="Create a minimal Sphinx docs skeleton.")
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    ap.add_argument("--force", action="store_true", help="Overwrite existing files if present")
    return ap

def main(argv: Optional[list[str]] = None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return

    ap = _build_run_parser()
    args = ap.parse_args(argv)
    cfg = RunConfig(
        plants=args.plant,
        tfinal=args.tfinal,
        dt=args.dt,
        wmin=args.wmin,
        wmax=args.wmax,
        npts=args.npts,
        plot_steps=args.plot_steps,
        plot_sigma=args.plot_sigma,
        show=args.show,
        save_png=args.save_png,
        save_json=args.save_json,
        title_prefix=args.title,
    )
    app = MIMOApp(level=_level(args.verbose))
    result = app.run(cfg)
    print(json_dumps(result.to_jsonable()))

def json_dumps(obj) -> str:
    import json
    def _default(o):
        if isinstance(o, complex):
            return {"re": o.real, "im": o.imag}
        return str(o)
    return json.dumps(obj, indent=2, default=_default)

if __name__ == "__main__":
    main()
