#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import importlib.util
import os
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Script mode: add repository root to sys.path, then import absolute modules.
    import sys

    PKG_DIR = os.path.abspath(os.path.dirname(__file__))
    REPO_ROOT = os.path.abspath(os.path.join(PKG_DIR, "..", ".."))
    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)

    from state_space_design.servoTool.apis import RunRequest, run
else:
    # Package mode: python -m state_space_design.servoTool.cli from repo root.
    from .apis import RunRequest, run


_PACKAGE = "state_space_design.servoTool"
_PROJECT = "modernControl - state_space_design.servoTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "state_space_design.servoTool.cli",
    "state_space_design.servoTool.apis",
]
_OPTIONAL_MODULES = [
    "state_space_design.servoTool.app",
    "state_space_design.servoTool.core",
    "state_space_design.servoTool.io",
    "state_space_design.servoTool.plotting",
    "state_space_design.servoTool.utils",
]

# When running inside the package, bare filenames should land in the local out folder.
OUT_DIR = os.path.join(os.path.dirname(__file__), "out")


def _module_exists(module_name: str) -> bool:
    """Return true when Python can locate the module without importing it."""
    try:
        return importlib.util.find_spec(module_name) is not None
    except (ImportError, ModuleNotFoundError, ValueError):
        return False


def _documented_modules() -> list[str]:
    """Return only importable modules so generated API docs avoid ghost modules."""
    modules: list[str] = []
    for module_name in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if module_name in modules:
            continue
        if module_name in _REQUIRED_MODULES or _module_exists(module_name):
            modules.append(module_name)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to path unless the file exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> servoTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _documented_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _ensure_out_dir() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)


def _maybe_prefix_outdir(name: Optional[str]) -> Optional[str]:
    """Prefix bare output filenames with the package out directory in script mode."""
    if not name:
        return None
    if os.path.dirname(name):
        return name
    if __package__ in (None, ""):
        _ensure_out_dir()
        return os.path.join(OUT_DIR, name)
    return name


def build_parser() -> argparse.ArgumentParser:
    """Build the command line parser for servoTool."""
    ap = argparse.ArgumentParser(
        prog="state_space_design.servoTool",
        description="Servo input-output model builder.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = ap.add_subparsers(dest="cmd")

    run_p = sub.add_parser(
        "run",
        help="build and simulate a servo input-output model",
        description="Build a servo input-output model from controller JSON data.",
    )
    run_p.add_argument(
        "--data",
        required=True,
        help="Controller JSON from gainMatrixTool output. Example in package mode: in/K_controller.json",
    )
    run_p.add_argument("--C", help="Output matrix C when needed and not present in the input JSON.")
    run_p.add_argument("--r", type=float, default=1.0, help="Reference step amplitude.")
    run_p.add_argument("--k_r", type=float, default=None, help="Override prefilter value for state-feedback mode.")
    run_p.add_argument("--t", default="0:0.01:5", help="Time vector such as 0:0.01:5 or 0,1,2.")
    run_p.add_argument(
        "--save_csv",
        default=None,
        help="CSV output path. In direct script mode, a bare filename is saved under the package out folder.",
    )
    run_p.add_argument(
        "--export_json",
        default=None,
        help="JSON output path. In direct script mode, a bare filename is saved under the package out folder.",
    )
    run_p.add_argument(
        "--backend",
        choices=["none", "mpl", "plotly", "both"],
        default="none",
        help="Optional quick-look plotting backend.",
    )
    run_p.add_argument("--no_show", action="store_true", help="Do not show interactive plot windows.")

    skel_p = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel_p.add_argument("dest", type=Path, help="Destination docs directory.")
    skel_p.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return ap


def _run_servo(args: argparse.Namespace) -> int:
    export_json = _maybe_prefix_outdir(args.export_json)
    save_csv = _maybe_prefix_outdir(args.save_csv)

    req = RunRequest(
        data_path=args.data,
        mode_C=args.C,
        r=args.r,
        k_r_override=args.k_r,
        t=args.t,
        save_csv=save_csv,
        export_json=export_json,
        backend=args.backend,
        no_show=args.no_show,
    )
    resp = run(req)

    print("\n== ServoTool results ==")
    print(f"mode: {resp.model.mode.value}, r: {resp.model.r}")
    if resp.model.k_r is not None:
        print(f"k_r: {resp.model.k_r:g}")
    if resp.model.kI is not None:
        print(f"kI: {resp.model.kI:g}")
    if resp.io_json_path:
        print(f"JSON: {resp.io_json_path}")
    if resp.csv_path:
        print(f"CSV : {resp.csv_path}")
    if resp.plot_html_path:
        print(f"Plot: {resp.plot_html_path}")
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the servoTool command line interface."""
    ap = build_parser()
    args = ap.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility for historical no-subcommand usage.
    if args.cmd is None:
        import sys

        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = ap.parse_args(["run", *legacy_args])
        else:
            ap.print_help()
            return 0

    if args.cmd == "run":
        return _run_servo(args)

    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
