# Generated by frequency_response.plotTool.cli
import sys
from pathlib import Path
# docs -> plotTool -> frequency_response -> <repo root>
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = 'modernControl - frequency_response.plotTool'
author = 'modernControl'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'furo'
html_static_path = ['_static']
autodoc_typehints = 'description'
