# -*- coding: utf-8 -*-
"""CLI entry point for state_space_design.minOrdTool."""
from __future__ import annotations

import argparse
import importlib.util
import logging
import os
import sys
from pathlib import Path


# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/minOrdTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.minOrdTool.apis import MinOrdRunRequest
    from state_space_design.minOrdTool.app import run_app
else:
    from .apis import MinOrdRunRequest
    from .app import run_app


_PACKAGE = "state_space_design.minOrdTool"
_PROJECT = "modernControl - state_space_design.minOrdTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "state_space_design.minOrdTool.cli",
    "state_space_design.minOrdTool.apis",
    "state_space_design.minOrdTool.app",
]
_OPTIONAL_MODULES = [
    "state_space_design.minOrdTool.core",
    "state_space_design.minOrdTool.design",
    "state_space_design.minOrdTool.io",
    "state_space_design.minOrdTool.utils",
]


def _module_exists(module_name: str) -> bool:
    """Return true when a module can be found without importing it."""
    try:
        return importlib.util.find_spec(module_name) is not None
    except Exception:
        return False


def _documented_modules() -> list[str]:
    """Return only modules that are safe for Sphinx autodoc to import."""
    modules = list(_REQUIRED_MODULES)
    modules.extend(mod for mod in _OPTIONAL_MODULES if _module_exists(mod))
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text unless the file already exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and gitkeep files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> minOrdTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build the Sphinx index page with safe heading syntax."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page from real importable modules only."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _documented_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _coalesce_negatives(argv: list[str] | None) -> list[str] | None:
    """Fold negative-looking pole values into equals-form argparse tokens."""
    if argv is None:
        return None

    sensitive = {"--poles", "--K_poles"}
    out: list[str] = []
    i = 0
    n = len(argv)

    def is_negative_value(tok: str) -> bool:
        return tok.startswith("-") and not tok.startswith("--")

    while i < n:
        tok = argv[i]
        if tok in sensitive:
            j = i + 1
            vals: list[str] = []
            while j < n and is_negative_value(argv[j]):
                vals.append(argv[j])
                j += 1
            if vals:
                out.append(f"{tok}=" + ",".join(vals))
                i = j
                continue
            out.append(tok)
            i += 1
            continue

        out.append(tok)
        i += 1

    return out


def _split_commas(seq: list[str] | None) -> list[str] | None:
    """Split comma-joined list tokens back into individual items."""
    if not seq:
        return seq
    out: list[str] = []
    for item in seq:
        if "," in item:
            out.extend(part for part in item.replace(",", " ").split() if part)
        else:
            out.append(item)
    return out


def build_parser() -> argparse.ArgumentParser:
    """Build the command line parser."""
    parser = argparse.ArgumentParser(
        prog="state_space_design.minOrdTool",
        description="Minimum-order observer design for scalar-output systems.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run a minimum-order observer design",
        description="Run a minimum-order observer design for a scalar-output state-space system.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    run.add_argument("--A", required=True, help='State matrix, for example "0 1; -2 -3".')
    run.add_argument("--B", default=None, help='Optional input matrix, for example "0; 1".')
    run.add_argument("--C", required=True, help='Output row, for example "1 0 0".')
    run.add_argument(
        "--poles",
        nargs="+",
        required=True,
        help="Observer poles. Equals-form also works, for example --poles=-10,-10.",
    )
    run.add_argument("--K", default=None, help='Optional state-feedback row, for example "90 29 4".')
    run.add_argument(
        "--K_poles",
        nargs="+",
        default=None,
        help="Optional poles used to design K. Equals-form is recommended for negative values.",
    )
    run.add_argument("--allow_pinv", action="store_true", help="Use pseudoinverse when the transformation is singular.")
    run.add_argument("--precision", type=int, default=4, help="Digits for human-readable numeric output.")
    run.add_argument("--pretty", action="store_true", help="Print human-readable derivation output.")
    run.add_argument("--export-json", default=None, help="Explicit JSON output path.")
    run.add_argument("--verbose", action="store_true", help="Enable debug logging.")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_design(args: argparse.Namespace) -> int:
    logging.basicConfig(
        level=(logging.DEBUG if args.verbose else logging.INFO),
        format="%(levelname)s: %(message)s",
    )

    args.poles = _split_commas(args.poles)
    if args.K_poles is not None:
        args.K_poles = _split_commas(args.K_poles)

    req = MinOrdRunRequest(
        A=args.A,
        B=args.B,
        C=args.C,
        poles=args.poles,
        K=args.K,
        K_poles=args.K_poles,
        allow_pinv=args.allow_pinv,
        precision=args.precision,
        pretty=args.pretty,
        export_json=args.export_json,
        verbose=args.verbose,
    )
    res = run_app(req)
    print(f"Saved JSON -> {res.json_path}")
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the minOrdTool command line interface."""
    raw_argv = list(argv) if argv is not None else sys.argv[1:]
    argv_norm = _coalesce_negatives(raw_argv)

    parser = build_parser()
    args = parser.parse_args(argv_norm)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility with the historical no-subcommand command shape.
    if args.cmd is None:
        if raw_argv and raw_argv[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            legacy_args = _coalesce_negatives(["run", *raw_argv])
            args = parser.parse_args(legacy_args)
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_design(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
