#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

"""Command-line interface for pid_controllers.zeroPoleTool.

The CLI supports both normal design runs and a small developer helper for
creating a Sphinx documentation skeleton.
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from this folder: add project root to sys.path.
    # .../modernControl/pid_controllers/zeroPoleTool/cli.py -> project root is two levels up.
    proj_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if proj_root not in sys.path:
        sys.path.insert(0, proj_root)

    # Import package modules via absolute path.
    from pid_controllers.zeroPoleTool.app import ZeroPoleApp, AppConfig  # type: ignore
else:
    # Normal package execution, for example:
    # python -m pid_controllers.zeroPoleTool.cli
    from .app import ZeroPoleApp, AppConfig


# -------------------------- Sphinx skeleton helper --------------------------

def _rst_heading(text: str, marker: str = "=") -> str:
    """Return a valid reStructuredText heading with a safe underline length."""
    return f"{text}\n{marker * len(text)}\n\n"


def _ensure_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and git-tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _write_if_allowed(path: Path, text: str, *, force: bool) -> None:
    """Write text unless the file already exists and force is false."""
    if path.exists() and not force:
        return
    path.write_text(text, encoding="utf-8")


def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    """Create a minimal Sphinx documentation skeleton for zeroPoleTool."""
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_support_dirs(dest)

    conf = (
        "# Generated by pid_controllers.zeroPoleTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> zeroPoleTool -> pid_controllers -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n\n"
        "project = 'digital-control - pid_controllers.zeroPoleTool'\n"
        "author = 'digital-control'\n\n"
        "extensions = [\n"
        "    'sphinx.ext.autodoc',\n"
        "    'sphinx.ext.napoleon',\n"
        "    'sphinx.ext.viewcode',\n"
        "]\n\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']\n"
        "html_theme = 'furo'\n"
        "html_static_path = ['_static']\n"
        "autodoc_typehints = 'description'\n"
        "napoleon_google_docstring = True\n"
        "napoleon_numpy_docstring = True\n"
    )

    title = "Welcome to pid_controllers.zeroPoleTool's documentation"
    index = (
        ".. pid_controllers.zeroPoleTool documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )

    api = (
        _rst_heading("API Reference", "=")
        + _rst_heading("Application Layer", "-")
        + ".. automodule:: pid_controllers.zeroPoleTool.app\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Core Computation", "-")
        + ".. automodule:: pid_controllers.zeroPoleTool.core\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Design Utilities", "-")
        + ".. automodule:: pid_controllers.zeroPoleTool.design\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Input and Output", "-")
        + ".. automodule:: pid_controllers.zeroPoleTool.io\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Utilities", "-")
        + ".. automodule:: pid_controllers.zeroPoleTool.utils\n"
        + "   :members:\n"
        + "   :undoc-members:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    _write_if_allowed(dest / "conf.py", conf, force=force)
    _write_if_allowed(dest / "index.rst", index, force=force)
    _write_if_allowed(dest / "api.rst", api, force=force)
    _write_if_allowed(dest / "Makefile", makefile, force=force)
    return dest


def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="sphinx-skel",
        description="Create a minimal Sphinx docs skeleton for zeroPoleTool.",
    )
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory. Default: docs")
    ap.add_argument("--force", action="store_true", help="Overwrite existing generated files")
    return ap


# ------------------------------ Main CLI ------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Two-DOF zero-placement design and analysis for zeroPoleTool")
    p.add_argument("--arch", choices=["fig8-31", "fig8-30"], default="fig8-31")

    g = p.add_argument_group("Plant")
    g.add_argument("--plant-form", choices=["coeff", "poly", "zpk"], required=True)
    g.add_argument("--num", type=str)
    g.add_argument("--den", type=str)
    g.add_argument("--num-poly", type=str)
    g.add_argument("--den-poly", type=str)
    g.add_argument("--gain", type=float)
    g.add_argument("--zeros", type=str)
    g.add_argument("--poles", type=str)

    grd = p.add_argument_group("Pole grid")
    grd.add_argument("--a-vals", type=str)
    grd.add_argument("--b-vals", type=str)
    grd.add_argument("--c-vals", type=str)
    grd.add_argument("--a-range", type=float, nargs=2)
    grd.add_argument("--a-n", type=int)
    grd.add_argument("--b-range", type=float, nargs=2)
    grd.add_argument("--b-n", type=int)
    grd.add_argument("--c-range", type=float, nargs=2)
    grd.add_argument("--c-n", type=int)

    r = p.add_argument_group("Requirements for reference step")
    r.add_argument("--os-min", type=float, default=0.0)
    r.add_argument("--os-max", type=float, default=100.0)
    r.add_argument("--ts-max", type=float, default=10.0)
    r.add_argument("--settle-tol", type=float, default=0.02)

    rank = p.add_argument_group("Ranking")
    rank.add_argument("--rank-dist-peak-weight", type=float, default=0.0)

    o = p.add_argument_group("Outputs")
    o.add_argument("--save-prefix", type=str, default="zp_design")
    o.add_argument("--plot-prefix", type=str, default="zp_design")
    o.add_argument("--export-json", action="store_true")
    o.add_argument("--export-csv", action="store_true")
    o.add_argument(
        "--plots",
        nargs="*",
        default=["step_ref"],
        choices=["step_ref", "step_dist", "ramp_ref", "accel_ref"],
    )

    b = p.add_argument_group("Behavior")
    b.add_argument("--best-effort", action="store_true")
    b.add_argument("--debug", action="store_true")
    b.add_argument("--no-progress", action="store_true")
    return p


def main(argv: Optional[list[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    # Developer/docs helper subcommand. This is intercepted before the normal
    # parser because the design CLI is flag-only.
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return 0

    args = build_parser().parse_args(argv)
    cfg = AppConfig(
        # Plant
        plant_form=args.plant_form,
        num=getattr(args, "num", None),
        den=getattr(args, "den", None),
        num_poly=getattr(args, "num_poly", None),
        den_poly=getattr(args, "den_poly", None),
        gain=getattr(args, "gain", None),
        zeros=getattr(args, "zeros", None),
        poles=getattr(args, "poles", None),
        # Architecture and grids
        arch=args.arch,
        a_vals=args.a_vals,
        b_vals=args.b_vals,
        c_vals=args.c_vals,
        a_range=args.a_range,
        a_n=args.a_n,
        b_range=args.b_range,
        b_n=args.b_n,
        c_range=args.c_range,
        c_n=args.c_n,
        # Specifications and behavior
        os_min=args.os_min,
        os_max=args.os_max,
        ts_max=args.ts_max,
        settle_tol=args.settle_tol,
        rank_dist_peak_weight=args.rank_dist_peak_weight,
        best_effort=args.best_effort,
        export_json=args.export_json,
        export_csv=args.export_csv,
        plots=args.plots,
        no_progress=args.no_progress,
        debug=args.debug,
        save_prefix=args.save_prefix,
        plot_prefix=args.plot_prefix,
    )
    ZeroPoleApp(cfg).run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
