# Generated by frequencyResponse.bodeTool.cli
import sys
from pathlib import Path
# docs -> bodeTool -> frequencyResponse -> <repo root>
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
project = 'modernControl – frequencyResponse.bodeTool'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'furo'
