# cli.py
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules
    _pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if _pkg_root not in sys.path:
        sys.path.insert(0, _pkg_root)

    from pid_controllers.tuningTool.app import TuningApp  # type: ignore
    from pid_controllers.tuningTool.utils import TuningInputs  # type: ignore
    from pid_controllers.tuningTool.tools.tool_paths import OUT_DIR, ensure_outdir  # type: ignore
else:
    # Normal package execution
    from .app import TuningApp
    from .utils import TuningInputs
    from .tools.tool_paths import OUT_DIR, ensure_outdir


# -------------------------- Sphinx skeleton helper --------------------------

def _rst_heading(text: str, char: str = "=") -> str:
    """Return a valid reStructuredText heading with a safe underline length."""
    return f"{text}\n{char * len(text)}\n\n"


def _ensure_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and .gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _write_file(path: Path, text: str, *, force: bool = False) -> None:
    """Write text unless the file already exists and force is disabled."""
    if path.exists() and not force:
        return
    path.write_text(text, encoding="utf-8")


def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    """
    Create a minimal Sphinx documentation skeleton for tuningTool.

    The generated files avoid fragile reStructuredText formatting by using
    dynamic heading underlines. Support directories include .gitkeep files so
    GitHub Pages builds do not fail because an expected static folder is absent.
    """
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_support_dirs(dest)

    conf = (
        "# Generated by pid_controllers.tuningTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> tuningTool -> pid_controllers -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n\n"
        "project = 'digitalControl - pid_controllers.tuningTool'\n"
        "author = 'digitalControl'\n\n"
        "extensions = [\n"
        "    'sphinx.ext.autodoc',\n"
        "    'sphinx.ext.napoleon',\n"
        "    'sphinx.ext.viewcode',\n"
        "]\n\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']\n"
        "html_theme = 'furo'\n"
        "html_static_path = ['_static']\n"
        "autodoc_typehints = 'description'\n"
        "napoleon_google_docstring = True\n"
        "napoleon_numpy_docstring = True\n"
    )

    title = "Welcome to pid_controllers.tuningTool's docs!"
    index = (
        ".. pid_controllers.tuningTool documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )

    api = (
        _rst_heading("API Reference", "=")
        + _rst_heading("Application Layer", "-")
        + ".. automodule:: pid_controllers.tuningTool.app\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("API Schemas", "-")
        + ".. automodule:: pid_controllers.tuningTool.apis\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Core Utilities", "-")
        + ".. automodule:: pid_controllers.tuningTool.utils\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Command Line Interface", "-")
        + ".. automodule:: pid_controllers.tuningTool.cli\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Tool Paths", "-")
        + ".. automodule:: pid_controllers.tuningTool.tools.tool_paths\n"
        + "   :members:\n"
        + "   :undoc-members:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    _write_file(dest / "conf.py", conf, force=force)
    _write_file(dest / "index.rst", index, force=force)
    _write_file(dest / "api.rst", api, force=force)
    _write_file(dest / "Makefile", makefile, force=force)
    return dest


def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="sphinx-skel",
        description="Create a minimal Sphinx docs skeleton for pid_controllers.tuningTool.",
    )
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    ap.add_argument("--force", action="store_true", help="Overwrite existing generated files if present")
    return ap


# ------------------------------ Main CLI parser ------------------------------

def _build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="pid_controllers.tuningTool",
        description="Query PID tuning rules from a JSON rule base.",
    )
    ap.add_argument(
        "--file",
        default="tuning_rules.json",
        help="Rules JSON file. Relative paths are resolved under pid_controllers/tuningTool/in.",
    )
    ap.add_argument("--method", help="Method key in JSON, such as ZN_step, ZN_ultimate, or CC_step.")
    ap.add_argument("--controller", help="Controller key in JSON, such as P, PI, or PID.")

    # Inputs are optional flags; validation is driven by the selected JSON method.
    ap.add_argument("--L", type=float, help="Process dead time L.")
    ap.add_argument("--T", type=float, help="Process time constant T.")
    ap.add_argument("--Kcr", type=float, help="Critical gain Kcr.")
    ap.add_argument("--Pcr", type=float, help="Critical period Pcr.")

    ap.add_argument("--precision", type=int, default=6, help="Digits for printed floats.")
    ap.add_argument(
        "--list",
        choices=["methods", "controllers", "formulas"],
        help="List available items. Use --method with controllers or formulas.",
    )
    ap.add_argument("--export-json", help="Write result JSON to pid_controllers/tuningTool/out/<name>.json")
    ap.add_argument("--export-csv", help="Write result CSV to pid_controllers/tuningTool/out/<name>.csv")
    return ap


def _validate_required_inputs(app: TuningApp, args: argparse.Namespace) -> tuple[bool, str]:
    # Load the JSON and fetch required inputs list for the method.
    data = app.repo.read_json(args.file)
    if args.method not in data.get("methods", {}):
        return False, f"Unknown method '{args.method}'. Try --list methods."

    req = list(data["methods"][args.method].get("inputs", []))
    missing = [name for name in req if getattr(args, name, None) is None]
    if missing:
        return (
            False,
            f"Method '{args.method}' requires inputs: {', '.join(req)}. "
            f"Missing: {', '.join(missing)}.",
        )

    if args.controller not in data["methods"][args.method].get("controllers", {}):
        return (
            False,
            f"Unknown controller '{args.controller}' for method '{args.method}'. "
            f"Try --list controllers --method {args.method}.",
        )

    return True, ""


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    # Developer/docs helper subcommand. This is intercepted before the normal
    # parser because the original tuning CLI is flag-only.
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return 0

    ap = _build_parser()
    args = ap.parse_args(argv)

    app = TuningApp.create_default()

    if args.list:
        if args.list == "methods":
            d = app.service.list_methods(file=args.file)
            for k, v in d.items():
                print(f"{k}: {v}")
            return 0

        if args.list == "controllers":
            if not args.method:
                print("Use --method with --list controllers")
                return 2
            try:
                lst = app.service.list_controllers(args.method, file=args.file)
            except KeyError as e:
                print(str(e))
                return 2
            print("Controllers:", ", ".join(lst))
            return 0

        if args.list == "formulas":
            if not args.method:
                print("Use --method with --list formulas")
                return 2
            try:
                d = app.service.list_formulas(args.method, file=args.file)
            except KeyError as e:
                print(str(e))
                return 2
            for c, f in d.items():
                print(f"{c}: Kp={f.get('Kp')}, Ti={f.get('Ti')}, Td={f.get('Td')}")
            return 0

    if not (args.method and args.controller):
        print("Nothing to do. Provide --method and --controller, or use --list.")
        return 0

    ok, msg = _validate_required_inputs(app, args)
    if not ok:
        print(msg)
        return 2

    inputs = TuningInputs(L=args.L, T=args.T, Kcr=args.Kcr, Pcr=args.Pcr)
    res = app.run_compute(method=args.method, controller=args.controller, inputs=inputs, file=args.file)

    # Late import to avoid cycles in shim mode.
    if __package__ in (None, ""):
        from pid_controllers.tuningTool.apis import PrintAPI, ExportAPI  # type: ignore
    else:
        from .apis import PrintAPI, ExportAPI

    text = PrintAPI().render_text(res, precision=args.precision)
    print(text)

    if args.export_json or args.export_csv:
        ensure_outdir()
        if args.export_json:
            data = ExportAPI().to_json(res)
            (OUT_DIR / args.export_json).write_text(json.dumps(data, indent=2), encoding="utf-8")
            print(f"Saved JSON -> {OUT_DIR / args.export_json}")

        if args.export_csv:
            fields = ["method", "controller", "Kp", "Ti", "Td", "Ki", "Kd"]
            with (OUT_DIR / args.export_csv).open("w", newline="", encoding="utf-8") as f:
                w = csv.writer(f)
                w.writerow(fields)
                w.writerow([res.method, res.controller, res.Kp, res.Ti, res.Td, res.Ki, res.Kd])
            print(f"Saved CSV  -> {OUT_DIR / args.export_csv}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
