#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import importlib.util
import logging
import os
import sys
from pathlib import Path

import numpy as np

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/regulatorTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.regulatorTool.utils import parse_real_vec, parse_complex_list
    from state_space_design.regulatorTool.apis import RegulatorRunRequest
    from state_space_design.regulatorTool.app import run_app
else:
    from .utils import parse_real_vec, parse_complex_list
    from .apis import RegulatorRunRequest
    from .app import run_app


_PACKAGE = "state_space_design.regulatorTool"
_PROJECT = "modernControl - state_space_design.regulatorTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "state_space_design.regulatorTool.cli",
    "state_space_design.regulatorTool.apis",
    "state_space_design.regulatorTool.app",
    "state_space_design.regulatorTool.utils",
]
_OPTIONAL_MODULES = [
    "state_space_design.regulatorTool.core",
    "state_space_design.regulatorTool.io",
    "state_space_design.regulatorTool.design",
    "state_space_design.regulatorTool.plotting",
]

# When running from inside regulatorTool, write artifacts to ./out by default.
OUT_DIR = "out"


def _available_modules() -> list[str]:
    """Return only importable modules so generated docs avoid ghost modules."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> regulatorTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _ensure_prefix_dir(prefix: str | None) -> str | None:
    """Place a bare save prefix under the local output directory."""
    if not prefix:
        return None
    dname = os.path.dirname(prefix)
    if not dname:
        os.makedirs(OUT_DIR, exist_ok=True)
        return os.path.join(OUT_DIR, prefix)
    os.makedirs(dname, exist_ok=True)
    return prefix


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="state_space_design.regulatorTool",
        description="Ogata 10-6 regulator with a minimum-order observer for SISO systems.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="run the regulator design workflow",
        description="Design and simulate a SISO regulator with a minimum-order observer.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    run.add_argument("--num", required=True, help='Plant numerator, for example "10 20".')
    run.add_argument("--den", required=True, help='Plant denominator, for example "1 10 24 0".')
    run.add_argument("--K_poles", default=None, help="Controller poles as a quoted comma-separated string.")
    run.add_argument("--obs_poles", default=None, help="Observer poles as a quoted comma-separated string.")

    run.add_argument("--ts", type=float, default=None, help="Settling time target in seconds.")
    run.add_argument("--undershoot", default=None, help="Undershoot range as low,high.")
    run.add_argument("--obs_speed_factor", type=float, default=5.0, help="Observer speed factor.")

    run.add_argument("--x0", default=None, help="Initial state vector.")
    run.add_argument("--e0", default=None, help="Initial observer error vector.")
    run.add_argument("--t_final", type=float, default=8.0, help="Final simulation time.")
    run.add_argument("--dt", type=float, default=0.01, help="Simulation time step.")

    run.add_argument("--pretty", action="store_true", help="Print human-readable equations when supported.")
    run.add_argument("--plots", choices=["none", "mpl", "plotly", "both"], default="both", help="Plot backend selection.")
    run.add_argument("--save_prefix", default=None, help="Prefix for saved figures or HTML files.")
    run.add_argument("--export_json", default=None, help="Write a JSON summary to this path.")

    run.add_argument("--rl_axes", default="-14,2,-8,8", help="Root-locus axes as xmin,xmax,ymin,ymax.")
    run.add_argument("--rl_k", default="auto", help="Root-locus gain sweep, or auto.")

    run.add_argument("--ply_width", type=int, default=0, help="Fixed Plotly width. Use 0 for responsive width.")
    run.add_argument("--verbose", action="store_true", help="Enable verbose logging.")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_regulator(args: argparse.Namespace) -> int:
    logging.basicConfig(
        level=(logging.DEBUG if args.verbose else logging.INFO),
        format="INFO: %(message)s",
    )

    num = parse_real_vec(args.num)
    den = parse_real_vec(args.den)
    k_poles = parse_complex_list(args.K_poles) if args.K_poles else None
    obs_poles = parse_complex_list(args.obs_poles) if args.obs_poles else None
    undershoot = tuple(float(x) for x in args.undershoot.replace(",", " ").split()) if args.undershoot else None
    rl_axes = tuple(float(x) for x in args.rl_axes.replace(",", " ").split())
    x0 = np.array([float(x) for x in args.x0.replace(",", " ").split()], float) if args.x0 else None
    e0 = np.array([float(x) for x in args.e0.replace(",", " ").split()], float) if args.e0 else None

    save_prefix = _ensure_prefix_dir(args.save_prefix)

    req = RegulatorRunRequest(
        num=num,
        den=den,
        K_poles=k_poles,
        obs_poles=obs_poles,
        ts=args.ts,
        undershoot=undershoot,
        obs_speed_factor=args.obs_speed_factor,
        x0=x0,
        e0=e0,
        t_final=args.t_final,
        dt=args.dt,
        rl_axes=rl_axes,
        rl_k=args.rl_k,
        pretty=args.pretty,
        plots=args.plots,
        save_prefix=save_prefix,
        export_json=args.export_json,
        ply_width=args.ply_width,
        verbose=args.verbose,
    )
    run_app(req)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the regulator command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility: allow historical usage without an explicit
    # subcommand, for example: python cli.py --num "10 20" --den "1 10 24 0".
    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_regulator(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
