#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path
from typing import Any

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside transient_analysis/routhTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from transient_analysis.routhTool.app import RouthApp
else:
    from .app import RouthApp


_PACKAGE = "transient_analysis.routhTool"
_PROJECT = "modernControl - transient_analysis.routhTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "transient_analysis.routhTool.cli",
    "transient_analysis.routhTool.app",
]
_OPTIONAL_MODULES = [
    "transient_analysis.routhTool.apis",
    "transient_analysis.routhTool.core",
    "transient_analysis.routhTool.design",
    "transient_analysis.routhTool.io",
    "transient_analysis.routhTool.utils",
]


def _available_modules() -> list[str]:
    """Return importable modules so generated docs avoid missing-module failures."""
    modules = list(_REQUIRED_MODULES)
    for mod in _OPTIONAL_MODULES:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> routhTool -> transient_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with safe heading formatting."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _available_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _print_table(array: Any, degrees: Any) -> None:
    """Print the Routh array in a compact console table."""
    colw = 14
    print("\nRouth array:")
    for deg, row in zip(degrees, array):
        cells = " ".join(f"{c:>{colw}}" for c in row)
        print(f"s^{deg:>2} | {cells}")


def _build_run_parser(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    """Attach the historical Routh options to a parser."""
    parser.add_argument(
        "--coeffs",
        required=True,
        help="Coefficients in descending powers, for example '1,5,6,K'.",
    )
    parser.add_argument(
        "--symbol",
        action="append",
        default=[],
        help="Symbolic parameter name. Repeat this option for multiple symbols.",
    )
    parser.add_argument(
        "--solve-for",
        default=None,
        help="Solve the first-column positivity conditions for this symbol.",
    )
    parser.add_argument("--eps", type=float, default=1e-9, help="Small epsilon for the epsilon trick.")
    parser.add_argument("--verify", action="store_true", help="Verify numeric cases with numpy.roots.")
    parser.add_argument("--hurwitz", action="store_true", help="Compute Hurwitz leading minors with SymPy.")
    parser.add_argument("--export", default=None, help="Basename for JSON export under the tool output folder.")
    return parser


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        prog="transient_analysis.routhTool",
        description="Routh array builder with numeric and symbolic support.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="build a Routh array",
        description="Build a Routh array and optionally compute stability conditions.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _build_run_parser(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _run_routh(args: argparse.Namespace) -> int:
    """Execute the Routh workflow and print a console report."""
    pkg_dir = Path(__file__).resolve().parent
    app = RouthApp.discover(pkg_dir)

    payload = app.run(
        args.coeffs,
        symbols=args.symbol,
        solve_for=args.solve_for,
        eps=args.eps,
        compute_hurwitz=args.hurwitz,
        verify_numeric=args.verify,
        export_basename=args.export,
    )

    _print_table(payload["routh_array"], payload["degrees"])
    print("\nFirst column:", payload["first_column"])
    print(f"\n#RHP roots by Routh (sign changes) = {payload['rhp_by_routh']}")
    if payload["rhp_by_roots"] is not None:
        print(f"#RHP roots by numpy.roots verification = {payload['rhp_by_roots']}")

    if payload["hurwitz_minors"]:
        print("\nHurwitz leading principal minors D1..Dn:")
        for i, d in enumerate(payload["hurwitz_minors"], 1):
            print(f"  D{i} = {d}")

    if payload["stability_condition"]:
        print(f"\nStability region from first-column positivity:\n  {payload['stability_condition']}")

    print("\nNotes:")
    for note in payload["notes"]:
        print("  -", note)

    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx skeleton and report written files."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def cli(argv: list[str] | None = None) -> int:
    """Run the Routh command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility: allow historical usage without an explicit
    # subcommand, for example: python cli.py --coeffs "1,5,6,K" --symbol K.
    if args.cmd is None:
        legacy_args = list(sys.argv[1:] if argv is None else argv)
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            legacy_parser = argparse.ArgumentParser(
                prog="transient_analysis.routhTool",
                description="Routh array builder with numeric and symbolic support.",
                formatter_class=argparse.ArgumentDefaultsHelpFormatter,
                allow_abbrev=False,
            )
            _build_run_parser(legacy_parser)
            args = legacy_parser.parse_args(legacy_args)
            return _run_routh(args)
        parser.print_help()
        return 0

    if args.cmd == "run":
        return _run_routh(args)

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(cli())
