#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

"""
pid_controllers.pidTool.cli

Command-line interface for the PID controller design tool.

Supported execution modes:
- Module mode: python -m pid_controllers.pidTool.cli
- Script mode from inside pid_controllers/pidTool: python cli.py

Developer helper:
- Generate a minimal Sphinx documentation skeleton:

      python -m pid_controllers.pidTool.cli sphinx-skel pid_controllers/pidTool/docs

The generated Sphinx files use dynamically sized reStructuredText headings and
include .gitkeep files inside support folders so GitHub Actions/Pages builds do
not fail because empty directories were not tracked by Git.
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside pid_controllers/pidTool.
    # Add the project root to sys.path so absolute imports work.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from pid_controllers.pidTool.core import tf_from_args, Requirements  # type: ignore
    from pid_controllers.pidTool.design import make_grids  # type: ignore
    from pid_controllers.pidTool.app import PIDDesignerApp  # type: ignore
else:
    # Normal package execution.
    from .core import tf_from_args, Requirements
    from .design import make_grids
    from .app import PIDDesignerApp


# -------------------------- Sphinx skeleton helper --------------------------

def _rst_heading(text: str, marker: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{marker * len(text)}\n\n"


def _ensure_support_dirs(dest: Path) -> None:
    """Create Sphinx support folders and .gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _write_if_allowed(path: Path, text: str, *, force: bool = False) -> None:
    """Write a generated file unless it already exists and force is false."""
    if path.exists() and not force:
        return
    path.write_text(text, encoding="utf-8")


def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    """
    Create a minimal Sphinx documentation skeleton for pidTool.

    The generated skeleton is intentionally conservative. It avoids fragile RST
    formatting, sizes all heading underlines dynamically, and writes .gitkeep
    files into Sphinx support folders so the directories are committed to Git.
    """
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_support_dirs(dest)

    conf = (
        "# Generated by pid_controllers.pidTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> pidTool -> pid_controllers -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n\n"
        "project = 'digitalControl - pid_controllers.pidTool'\n"
        "author = 'digitalControl'\n\n"
        "extensions = [\n"
        "    'sphinx.ext.autodoc',\n"
        "    'sphinx.ext.napoleon',\n"
        "    'sphinx.ext.viewcode',\n"
        "]\n\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']\n"
        "html_theme = 'furo'\n"
        "html_static_path = ['_static']\n\n"
        "autodoc_typehints = 'description'\n"
        "napoleon_google_docstring = True\n"
        "napoleon_numpy_docstring = True\n"
    )

    title = "Welcome to pid_controllers.pidTool's documentation"
    index = (
        ".. pid_controllers.pidTool documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )

    api = (
        _rst_heading("API Reference", "=")
        + _rst_heading("Application Layer", "-")
        + ".. automodule:: pid_controllers.pidTool.app\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Core Models and Utilities", "-")
        + ".. automodule:: pid_controllers.pidTool.core\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Design Engine", "-")
        + ".. automodule:: pid_controllers.pidTool.design\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Input and Output Helpers", "-")
        + ".. automodule:: pid_controllers.pidTool.io\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Command-Line Interface", "-")
        + ".. automodule:: pid_controllers.pidTool.cli\n"
        + "   :members:\n"
        + "   :undoc-members:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    _write_if_allowed(dest / "conf.py", conf, force=force)
    _write_if_allowed(dest / "index.rst", index, force=force)
    _write_if_allowed(dest / "api.rst", api, force=force)
    _write_if_allowed(dest / "Makefile", makefile, force=force)
    return dest


def _build_sphinx_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="sphinx-skel",
        description="Create a minimal Sphinx docs skeleton for pidTool.",
    )
    parser.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files if present")
    return parser


# ------------------------------ CLI parser ----------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="PID design via computational optimization (OOP)")
    sub = p.add_subparsers(dest="cmd", required=True)

    run = sub.add_parser("run", help="run a PID design search")

    # Plant input.
    run.add_argument("--plant-form", choices=["coeff", "poly", "zpk"], required=True)
    run.add_argument("--num", type=str)
    run.add_argument("--den", type=str)
    run.add_argument("--num-poly", type=str)
    run.add_argument("--den-poly", type=str)
    run.add_argument("--gain", type=float)
    run.add_argument("--zeros", type=str)
    run.add_argument("--poles", type=str)

    # Controller structure.
    run.add_argument("--structure", choices=["pid", "pi", "pd", "pid_dz"], default="pid_dz")

    # PID grids.
    run.add_argument("--Kp-vals", type=str)
    run.add_argument("--Ki-vals", type=str)
    run.add_argument("--Kd-vals", type=str)
    run.add_argument("--Kp-range", type=float, nargs=2)
    run.add_argument("--Ki-range", type=float, nargs=2)
    run.add_argument("--Kd-range", type=float, nargs=2)
    run.add_argument("--Kp-n", type=int)
    run.add_argument("--Ki-n", type=int)
    run.add_argument("--Kd-n", type=int)

    # PI grids.
    run.add_argument("--pi-Kp-vals", type=str)
    run.add_argument("--pi-Ki-vals", type=str)
    run.add_argument("--pi-Kp-range", type=float, nargs=2)
    run.add_argument("--pi-Ki-range", type=float, nargs=2)
    run.add_argument("--pi-Kp-n", type=int)
    run.add_argument("--pi-Ki-n", type=int)

    # PD grids.
    run.add_argument("--pd-Kp-vals", type=str)
    run.add_argument("--pd-Kd-vals", type=str)
    run.add_argument("--pd-Kp-range", type=float, nargs=2)
    run.add_argument("--pd-Kd-range", type=float, nargs=2)
    run.add_argument("--pd-Kp-n", type=int)
    run.add_argument("--pd-Kd-n", type=int)

    # Double-zero PID grids.
    run.add_argument("--K-vals", type=str)
    run.add_argument("--a-vals", type=str)
    run.add_argument("--K-range", type=float, nargs=2)
    run.add_argument("--a-range", type=float, nargs=2)
    run.add_argument("--K-n", type=int)
    run.add_argument("--a-n", type=int)

    # Requirements.
    run.add_argument("--max-overshoot", type=float)
    run.add_argument("--max-settling", type=float)
    run.add_argument("--max-rise", type=float)
    run.add_argument("--max-ess", type=float)
    run.add_argument("--settle-tol", type=float, default=0.02)

    # Objective.
    run.add_argument("--objective", choices=["itae", "ise", "ts", "mp", "weighted"], default="itae")
    run.add_argument("--w-ts", type=float, default=1.0)
    run.add_argument("--w-mp", type=float, default=0.1)
    run.add_argument("--w-itae", type=float, default=1.0)
    run.add_argument("--w-ise", type=float, default=0.0)

    # Simulation.
    run.add_argument("--tfinal", type=float)
    run.add_argument("--dt", type=float)

    # Outputs.
    run.add_argument("--backend", choices=["mpl", "plotly", "none"], default="plotly")
    run.add_argument("--plot-top", type=int, default=5)
    run.add_argument("--no-plot", action="store_true")
    run.add_argument("--save-prefix", type=str, default="design")
    run.add_argument("--export-json", action="store_true")
    run.add_argument("--export-csv", action="store_true")

    return p


# ------------------------------ Main entry ----------------------------------

def main(argv: Optional[list[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    # Developer/docs helper subcommand.
    # This must be intercepted before the normal parser because the original
    # CLI is subcommand-based and otherwise would reject the helper command.
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return 0

    p = build_parser()
    args = p.parse_args(argv)

    if args.cmd == "run":
        Gp = tf_from_args(args)
        grids = make_grids(args)
        req = Requirements(
            max_overshoot=args.max_overshoot,
            max_settling=args.max_settling,
            max_rise=args.max_rise,
            max_ess=args.max_ess,
            settle_tol=args.settle_tol,
        )
        app = PIDDesignerApp(out_dir=None)
        backend = "none" if args.no_plot else args.backend
        app.run(
            Gp=Gp,
            structure=args.structure,
            req=req,
            grids=grids,
            objective=args.objective,
            weights=(args.w_ts, args.w_mp, args.w_itae, args.w_ise),
            tfinal=args.tfinal,
            dt=args.dt,
            backend=backend,
            plot_top=args.plot_top,
            save_prefix=args.save_prefix,
            export_json=args.export_json,
            export_csv=args.export_csv,
        )
        return 0

    p.error(f"Unsupported command: {args.cmd}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
