#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

"""Command-line interface for ``pid_controllers.rootLocusTool``.

The CLI supports normal root-locus analysis and a small developer helper for
creating a Sphinx documentation skeleton.
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from pid_controllers.rootLocusTool.app import RootLocusApp  # type: ignore
else:
    from .app import RootLocusApp


# -------------------------- Sphinx skeleton helper --------------------------

def _rst_heading(text: str, char: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{char * len(text)}\n\n"


def _ensure_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with .gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    """Create a minimal Sphinx documentation skeleton under ``dest``."""
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_support_dirs(dest)

    conf = (
        "# Generated by pid_controllers.rootLocusTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "# docs -> rootLocusTool -> pid_controllers -> <repo root>\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n\n"
        "project = 'digital-control - pid_controllers.rootLocusTool'\n"
        "author = 'digital-control'\n\n"
        "extensions = [\n"
        "    'sphinx.ext.autodoc',\n"
        "    'sphinx.ext.napoleon',\n"
        "    'sphinx.ext.viewcode',\n"
        "]\n\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']\n"
        "html_theme = 'furo'\n"
        "html_static_path = ['_static']\n\n"
        "autodoc_typehints = 'description'\n"
        "napoleon_google_docstring = True\n"
        "napoleon_numpy_docstring = True\n"
    )

    title = "Welcome to pid_controllers.rootLocusTool's docs!"
    index = (
        ".. pid_controllers.rootLocusTool documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )

    api = (
        _rst_heading("API Reference", "=")
        + _rst_heading("Application Layer", "-")
        + ".. automodule:: pid_controllers.rootLocusTool.app\n"
        + "   :members:\n"
        + "   :undoc-members:\n\n"
        + _rst_heading("Command Line Interface", "-")
        + ".. automodule:: pid_controllers.rootLocusTool.cli\n"
        + "   :members:\n"
        + "   :undoc-members:\n"
    )

    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )

    def _write(path: Path, text: str) -> None:
        if path.exists() and not force:
            return
        path.write_text(text, encoding="utf-8")

    _write(dest / "conf.py", conf)
    _write(dest / "index.rst", index)
    _write(dest / "api.rst", api)
    _write(dest / "Makefile", makefile)
    return dest


def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="sphinx-skel",
        description="Create a minimal Sphinx docs skeleton for rootLocusTool.",
    )
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    ap.add_argument("--force", action="store_true", help="Overwrite existing files if present")
    return ap


# ------------------------------ Main CLI -----------------------------------

def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Root-locus with zeta-rays and design-point visualization")
    ap.add_argument("--example", choices=["ogata_8_1"], help="Preset plant")
    ap.add_argument("--num", help="Numerator coefficients as CSV or space-separated values")
    ap.add_argument("--den", help="Denominator coefficients as CSV or space-separated values")

    # Design scan
    ap.add_argument("--zeta_values", nargs="+", type=float, help="Explicit zeta list with values between 0 and 1")
    ap.add_argument(
        "--zeta_range",
        nargs=2,
        type=float,
        metavar=("ZMIN", "ZMAX"),
        help="Scan zeta range with 0 < ZMIN < ZMAX < 1",
    )
    ap.add_argument("--zeta_n", type=int, default=4, help="Number of zeta samples in range")
    ap.add_argument(
        "--omega",
        nargs=3,
        type=float,
        metavar=("WMIN", "WMAX", "WN"),
        default=[0.2, 12.0, 300],
        help="Omega grid: min max N for the angle scan",
    )
    ap.add_argument("--kmin", type=int, default=-1)
    ap.add_argument("--kmax", type=int, default=1)
    ap.add_argument("--a", dest="a_override", type=float, help="Override zero location a for plotting, with zeros at s=-a")

    # Rays clipping and axes
    ap.add_argument("--ray_wmin", type=float, default=0.0, help="Lower omega bound for zeta-rays on the plot")
    ap.add_argument("--ray_scale", type=float, default=1.05, help="If no --ylim, use ray_scale times max absolute imaginary locus value")
    ap.add_argument("--xlim", nargs=2, type=float, help="x-axis limits: xmin xmax")
    ap.add_argument("--ylim", nargs=2, type=float, help="y-axis limits: ymin ymax")

    # Plotting and IO
    ap.add_argument("--backend", choices=["mpl", "plotly"], default="plotly")
    ap.add_argument("--save", help="Save plot, using PNG for Matplotlib or HTML for Plotly, in ./out/ when relative")
    ap.add_argument("--title", default="Root Locus with zeta-rays")
    ap.add_argument("--no_plot", action="store_true")

    # Exports and analysis
    ap.add_argument("--export_json", help="Export summary JSON in ./out/ when relative")
    ap.add_argument("--export_csv", help="Export detailed rows CSV in ./out/ when relative")
    ap.add_argument("--analyze", action="store_true")
    ap.add_argument("--settle", type=float, default=0.02)
    ap.add_argument("--precision", type=int, default=6)
    return ap


def _format_value(value: object, precision: int = 6) -> str:
    """Format numeric values compactly for command-line output."""
    if isinstance(value, (int, float)):
        return f"{float(value):.{precision}g}"
    return str(value)


def main(argv: Optional[list[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    # Developer/docs helper subcommand. This is intercepted before the normal
    # parser so the legacy flag-only CLI remains unchanged.
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return 0

    ap = build_parser()
    args = ap.parse_args(argv)
    app = RootLocusApp()

    if getattr(args, "no_plot", False):
        args.save = None  # Compute and export only.

    result = app.run(
        example=args.example,
        num=args.num,
        den=args.den,
        backend=args.backend,
        save=args.save,
        export_json=args.export_json,
        export_csv=args.export_csv,
        zeta_values=args.zeta_values,
        zeta_range=args.zeta_range,
        zeta_n=args.zeta_n,
        omega=(args.omega[0], args.omega[1], int(args.omega[2])),
        kmin=args.kmin,
        kmax=args.kmax,
        a_override=args.a_override,
        ray_wmin=args.ray_wmin,
        ray_scale=args.ray_scale,
        xlim=tuple(args.xlim) if args.xlim else None,
        ylim=tuple(args.ylim) if args.ylim else None,
        title=args.title,
        analyze=args.analyze,
        settle=args.settle,
        precision=args.precision,
    )

    print("=== Root-Locus (OOP) ===")
    print(f"a_plot={_format_value(result['a_plot'])}; limits x={result['xlim']} y={result['ylim']}")

    if result.get("s_row"):
        s = result["s_row"]
        print(
            "s*: "
            f"zeta={_format_value(s['zeta'])}, "
            f"omega={_format_value(s['omega'])}, "
            f"a={_format_value(s['a'])}, "
            f"Kp={_format_value(s['Kp'])}, "
            f"Ti={_format_value(s['Ti'])}, "
            f"Td={_format_value(s['Td'])}"
        )

    if result.get("json_path"):
        print(f"Saved JSON -> {result['json_path']}")
    if result.get("csv_path"):
        print(f"Saved CSV  -> {result['csv_path']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
