# -*- coding: utf-8 -*-
"""
CLI entry point for minOrdTfTool.

The command can be executed from the project root with python -m, or directly
from inside the tool folder with python cli.py.
"""
from __future__ import annotations

import argparse
import importlib.util
import logging
import os
import sys
from pathlib import Path

import numpy as np

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/minOrdTfTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.minOrdTfTool.utils import parse_mat, split_tokens_any, parse_cplx_tokens
    from state_space_design.minOrdTfTool.app import MinOrdTfApp
else:
    from .utils import parse_mat, split_tokens_any, parse_cplx_tokens
    from .app import MinOrdTfApp


_PACKAGE = "state_space_design.minOrdTfTool"
_PROJECT = "modernControl - state_space_design.minOrdTfTool"
_AUTHOR = "modernControl"

_REQUIRED_MODULES = [
    "state_space_design.minOrdTfTool.cli",
    "state_space_design.minOrdTfTool.app",
    "state_space_design.minOrdTfTool.utils",
]

_OPTIONAL_MODULES = [
    "state_space_design.minOrdTfTool.apis",
    "state_space_design.minOrdTfTool.core",
    "state_space_design.minOrdTfTool.io",
    "state_space_design.minOrdTfTool.design",
    "state_space_design.minOrdTfTool.plotting",
]


def _real_modules() -> list[str]:
    """Return only modules that Python can import or locate."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if importlib.util.find_spec(mod) is not None:
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a valid underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> minOrdTfTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _real_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _normalize_negative_list_args(argv: list[str] | None) -> list[str] | None:
    """Normalize list options whose values may start with a minus sign."""
    if argv is None:
        return None
    out: list[str] = []
    i = 0
    sensitive = {"--K_poles", "--poles"}

    while i < len(argv):
        tok = argv[i]
        if tok in sensitive and i + 1 < len(argv):
            nxt = argv[i + 1]
            if nxt.startswith("-") and not nxt.startswith("--"):
                out.append(f"{tok}={nxt}")
                i += 2
                continue
        out.append(tok)
        i += 1

    return out


def _add_run_arguments(ap: argparse.ArgumentParser) -> None:
    """Add the original minOrdTfTool run arguments to a parser."""
    ap.add_argument("--A", required=True, help='State matrix, for example "0 1; -2 -3".')
    ap.add_argument("--B", required=True, help='Input matrix, for example "0; 1".')
    ap.add_argument("--C", required=True, help='Output matrix for the single-output case, for example "1 0".')
    ap.add_argument("--poles", nargs="+", required=True, help="Observer pole tokens. Use conjugate pairs when complex.")
    ap.add_argument("--K", default=None, help='Explicit state-feedback row, for example "90 29 4".')
    ap.add_argument("--K_poles", default=None, nargs="+", help="Design K from desired closed-loop poles.")
    ap.add_argument("--allow_pinv", action="store_true", help="Use a pseudoinverse for diagnostic cases when S is singular.")
    ap.add_argument("--precision", type=int, default=6)
    ap.add_argument("--pretty", action="store_true")
    ap.add_argument("--export_json", default=None, help="Path for the JSON export.")
    ap.add_argument("--log", default="INFO", choices=["CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"])
    ap.add_argument("--version", action="store_true", help="Print version information and exit.")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    ap = argparse.ArgumentParser(
        prog="state_space_design.minOrdTfTool",
        description="Minimum-order observer-based controller transfer function for the single-output case.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    sub = ap.add_subparsers(dest="cmd")

    run = sub.add_parser("run", help="Run the minimum-order observer controller calculation.")
    _add_run_arguments(run)

    skel = sub.add_parser("sphinx-skel", help="Create a deploy-safe Sphinx documentation skeleton for this package.")
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return ap


def _echo_version() -> None:
    """Print package version information."""
    try:
        from importlib.metadata import PackageNotFoundError, version

        try:
            version_text = version("modernControl")
        except PackageNotFoundError:
            version_text = "0.0.0+local"
    except Exception:
        version_text = "0.0.0+local"

    print(f"minOrdTfTool (modernControl) version: {version_text}")


def _run_tool(args: argparse.Namespace) -> int:
    """Execute the original minimum-order observer controller workflow."""
    if args.version:
        _echo_version()
        return 0

    logging.basicConfig(level=getattr(logging, args.log), format="%(levelname)s: %(message)s")

    try:
        A = parse_mat(args.A)
        B = parse_mat(args.B)
        C = parse_mat(args.C)
        if C.ndim == 1:
            C = C.reshape(1, -1)

        obs_poles = parse_cplx_tokens(args.poles)

        K = parse_mat(args.K) if args.K else None
        K_poles_tokens = None
        if args.K_poles:
            joined = " ".join(args.K_poles) if isinstance(args.K_poles, list) else args.K_poles
            K_poles_tokens = split_tokens_any(joined) if "," in joined else joined.split()
    except Exception as exc:
        logging.error("Failed to parse inputs: %s", exc)
        return 2

    app = MinOrdTfApp()
    try:
        resp = app.run(
            A=A,
            B=B,
            C=C,
            obs_poles=obs_poles,
            K=K,
            K_poles_tokens=K_poles_tokens,
            allow_pinv=args.allow_pinv,
            pretty=args.pretty,
            precision=args.precision,
            export_json=args.export_json,
        )
    except Exception:
        logging.exception("minOrdTfTool failed")
        return 1

    num = np.asarray(resp.tf_num, float)
    den = np.asarray(resp.tf_den, float)
    print("\nController TF  Gc(s) = U(s)/(-Y(s))")
    print("num:", [float(v) for v in num])
    print("den:", [float(v) for v in den])
    if resp.json_path:
        print(f"Saved JSON -> {resp.json_path}")

    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the minOrdTfTool command line interface."""
    argv = _normalize_negative_list_args(list(argv) if argv is not None else sys.argv[1:])
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    # Backward compatibility: preserve historical no-subcommand usage.
    if args.cmd is None:
        legacy_args = list(argv or [])
        if legacy_args and legacy_args[0] not in {"run", "sphinx-skel", "-h", "--help"}:
            args = parser.parse_args(["run", *legacy_args])
        else:
            parser.print_help()
            return 0

    if args.cmd == "run":
        return _run_tool(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
