#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_analysis/stateTransTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_analysis.stateTransTool.apis import StateTransRequest
    from state_space_analysis.stateTransTool.app import run as run_app
else:
    from .apis import StateTransRequest
    from .app import run as run_app


_PACKAGE = "state_space_analysis.stateTransTool"
_PROJECT = "modernControl - state_space_analysis.stateTransTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_analysis.stateTransTool.cli",
    "state_space_analysis.stateTransTool.apis",
    "state_space_analysis.stateTransTool.app",
    "state_space_analysis.stateTransTool.core",
    "state_space_analysis.stateTransTool.design",
    "state_space_analysis.stateTransTool.io",
    "state_space_analysis.stateTransTool.utils",
]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> stateTransTool -> state_space_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate the state-transition matrix from a SISO transfer function."
    )
    sub = p.add_subparsers(dest="cmd")

    run = sub.add_parser(
        "run",
        help="Generate the state-transition matrix from a SISO transfer function.",
        description="Generate the state-transition matrix from a SISO transfer function.",
    )
    _add_run_arguments(run)

    skel = sub.add_parser(
        "sphinx-skel",
        help="Create a deploy-safe Sphinx documentation skeleton for this package.",
    )
    skel.add_argument("dest", type=Path, help="Destination documentation directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    # Backward-compatible no-subcommand mode: if the first argument is not a known
    # subcommand, main() will parse the original state-transition options directly.
    _add_run_arguments(p)
    return p


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    g_in = p.add_argument_group("Input")
    g_in.add_argument("--tf", type=str, help='Rational expression in s, for example "(s+3)/(s^2+3*s+2)".')
    g_in.add_argument("--num", type=str, help='Numerator as CSV "1,3" or polynomial "s+3".')
    g_in.add_argument("--den", type=str, help='Denominator as CSV "1,3,2" or polynomial "s^2+3*s+2".')
    g_in.add_argument("--example", type=str, choices=["ogata_9_1"], help="Prefill Example 9-1 transfer function.")

    g_opt = p.add_argument_group("Options")
    g_opt.add_argument(
        "--canonical",
        default="controllable",
        choices=["controllable", "observable", "diagonal", "jordan"],
        help="State realization used to generate the transition matrix. Default: controllable.",
    )
    g_opt.add_argument("--eval", type=float, dest="eval_time", help="Evaluate the transition matrix at this time.")
    g_opt.add_argument("--inverse", action="store_true", help="Also output the inverse transition matrix.")
    g_opt.add_argument("--numeric", action="store_true", help="Print numeric matrices when evaluation time is provided.")
    g_opt.add_argument("--digits", type=int, default=8, help="Digits for numeric print.")
    g_opt.add_argument("--pretty", action="store_true", help="Print pretty symbolic matrices.")
    g_opt.add_argument("--export-json", type=str, help="Write transition-matrix results to JSON.")
    g_opt.add_argument("--log", type=str, default="INFO", dest="log_level", help="Logging level.")


def _run_from_args(args: argparse.Namespace) -> int:
    req = StateTransRequest(
        tf=args.tf,
        num=args.num,
        den=args.den,
        example=args.example,
        canonical=args.canonical,
        eval_time=args.eval_time,
        inverse=args.inverse,
        numeric=args.numeric,
        digits=args.digits,
        pretty=args.pretty,
        export_json=args.export_json,
        log_level=args.log_level,
    )
    out = run_app(req)
    print(out)
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    dest = Path(args.dest)
    written = _write_sphinx_skeleton(dest, force=bool(args.force))
    print(f"Sphinx skeleton ready: {dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {dest / '_static' / '.gitkeep'}")
    print(f"  {dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else list(argv)

    # Preserve the historical invocation style:
    #   python cli.py --tf ...
    # while also supporting:
    #   python cli.py run --tf ...
    #   python cli.py sphinx-skel docs --force
    if argv and argv[0] in {"run", "sphinx-skel"}:
        parser = build_parser()
        args = parser.parse_args(argv)
        if args.cmd == "sphinx-skel":
            return _run_sphinx_skel(args)
        return _run_from_args(args)

    run_parser = argparse.ArgumentParser(
        description="Generate the state-transition matrix from a SISO transfer function."
    )
    _add_run_arguments(run_parser)
    args = run_parser.parse_args(argv)
    return _run_from_args(args)


if __name__ == "__main__":
    raise SystemExit(main())
