from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_analysis/converterTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_analysis.converterTool.apis import RunRequest
    from state_space_analysis.converterTool.app import ConverterApp
else:
    from .apis import RunRequest
    from .app import ConverterApp


_PACKAGE = "state_space_analysis.converterTool"
_PROJECT = "modernControl - state_space_analysis.converterTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_analysis.converterTool.cli",
    "state_space_analysis.converterTool.apis",
    "state_space_analysis.converterTool.app",
    "state_space_analysis.converterTool.core",
    "state_space_analysis.converterTool.design",
    "state_space_analysis.converterTool.io",
    "state_space_analysis.converterTool.utils",
]


# -----------------------------------------------------------------------------
# Sphinx skeleton helpers
# -----------------------------------------------------------------------------

def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with an underline of matching length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text unless the file already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and gitkeep files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> converterTool -> state_space_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with safe heading formatting."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build a simple API page using automodule directives."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal Sphinx Makefile used across the project."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


# -----------------------------------------------------------------------------
# Existing converter CLI
# -----------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    """Build the command line parser for transfer-function and state-space conversion."""
    p = argparse.ArgumentParser(description="Convert between transfer-function and state-space models.")

    sub = p.add_subparsers(dest="cmd")

    # Backward-compatible default command: existing flags still work without a subcommand.
    _add_run_arguments(p)

    run = sub.add_parser("run", help="Convert between transfer-function and state-space models.")
    _add_run_arguments(run)

    skel = sub.add_parser("sphinx-skel", help="Create a deploy-safe Sphinx documentation skeleton for this package.")
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return p


def _add_run_arguments(p: argparse.ArgumentParser) -> None:
    """Add converter run arguments to an argparse parser."""
    p.add_argument("--num", type=str, help="Transfer-function numerator coefficients in descending powers.")
    p.add_argument("--den", type=str, help="Transfer-function denominator coefficients in descending powers.")
    p.add_argument("--A", type=str)
    p.add_argument("--B", type=str)
    p.add_argument("--C", type=str)
    p.add_argument("--D", type=str)
    p.add_argument("--iu", type=int, default=0, help="Input channel using zero-based indexing for state-space step plots.")
    p.add_argument("--tfinal", type=float, default=8.0)
    p.add_argument("--dt", type=float, default=1e-3)
    p.add_argument("--no-plot", dest="no_plot", action="store_true", help="Skip plotting.")
    p.add_argument("--sympy", action="store_true", help="Print a SymPy transfer function for SISO cases.")
    p.add_argument("--out-prefix", type=str, help="Prefix for files saved under the package out directory.")
    p.add_argument("--log", type=str, default="INFO", help="Log level: DEBUG, INFO, WARNING, or ERROR.")


def args_to_request(args: argparse.Namespace) -> RunRequest:
    """Convert parsed command line arguments into a RunRequest."""
    return RunRequest(
        num=args.num,
        den=args.den,
        A=args.A,
        B=args.B,
        C=args.C,
        D=args.D,
        iu=args.iu,
        tfinal=args.tfinal,
        dt=args.dt,
        sympy=args.sympy,
        no_plot=args.no_plot,
        out_prefix=args.out_prefix,
        log=args.log,
    )


def _handle_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate Sphinx files and print the created or updated paths."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv=None) -> None:
    """Run the converter command line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if getattr(args, "cmd", None) == "sphinx-skel":
        raise SystemExit(_handle_sphinx_skel(args))

    app = ConverterApp()
    res = app.run(args_to_request(args))
    raise SystemExit(0 if res.ok else 1)


if __name__ == "__main__":
    main()
