
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from control_systems.converterTool.apis import ConverterConfig
    from control_systems.converterTool.app import ConverterApp
else:
    from .apis import ConverterConfig
    from .app import ConverterApp

def _level(v: int):
    return logging.DEBUG if v >= 2 else (logging.INFO if v == 1 else logging.INFO)

# -------------------------- Sphinx skeleton helper --------------------------
def _write_sphinx_skel(dest: Path, force: bool = False) -> Path:
    dest.mkdir(parents=True, exist_ok=True)
    conf = (
        "# Generated by control_systems.converterTool.cli\n"
        "import sys\n"
        "from pathlib import Path\n"
        "ROOT = Path(__file__).resolve().parents[3]\n"
        "sys.path.insert(0, str(ROOT))\n"
        "project = 'modernControl – control_systems.converterTool'\n"
        "extensions = ['sphinx.ext.autodoc','sphinx.ext.napoleon','sphinx.ext.viewcode']\n"
        "templates_path = ['_templates']\n"
        "exclude_patterns = []\n"
        "html_theme = 'furo'\n"
    )
    index = (
        ".. control_systems.converterTool documentation master file\n\n"
        "Welcome to converterTool's docs!\n"
        "================================\n\n"
        ".. toctree::\n"
        "   :maxdepth: 2\n"
        "   :caption: Contents:\n\n"
        "   api\n"
    )
    api = (
        "API Reference\n"
        "=============\n\n"
        ".. automodule:: control_systems.converterTool.app\n"
        "   :members:\n"
        "   :undoc-members:\n\n"
        ".. automodule:: control_systems.converterTool.apis\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: control_systems.converterTool.core\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: control_systems.converterTool.io\n"
        "   :members:\n"
        "   :undoc-members:\n"
        ".. automodule:: control_systems.converterTool.design\n"
        "   :members:\n"
        "   :undoc-members:\n"
    )
    makefile = (
        "# Minimal Sphinx Makefile\n"
        ".PHONY: html clean\n"
        "html:\n\t+sphinx-build -b html . _build/html\n"
        "clean:\n\t+rm -rf _build\n"
    )
    def _write(path: Path, text: str):
        if path.exists() and not force:
            return
        path.write_text(text, encoding="utf-8")
    (dest / "_templates").mkdir(exist_ok=True)
    (dest / "_static").mkdir(exist_ok=True)
    _write(dest / "conf.py", conf)
    _write(dest / "index.rst", index)
    _write(dest / "api.rst", api)
    _write(dest / "Makefile", makefile)
    return dest

# ------------------------------ CLI parsers --------------------------------
def _build_run_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Convert between TF and SS (Ogata §2-6).")
    ap.add_argument("--num"); ap.add_argument("--den")
    ap.add_argument("--A"); ap.add_argument("--B"); ap.add_argument("--C"); ap.add_argument("--D")
    ap.add_argument("--iu", type=int, default=0)
    ap.add_argument("--tfinal", type=float, default=8.0)
    ap.add_argument("--dt", type=float, default=1e-3)
    ap.add_argument("--no-plot", action="store_true")
    ap.add_argument("--sympy", action="store_true")
    ap.add_argument("--save-json")
    ap.add_argument("-v","--verbose", action="count", default=0)
    return ap

def _build_sphinx_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="sphinx-skel", description="Create a minimal Sphinx docs skeleton.")
    ap.add_argument("dest", nargs="?", default="docs", help="Destination directory (default: docs)")
    ap.add_argument("--force", action="store_true", help="Overwrite existing files if present")
    return ap

def main(argv: Optional[list[str]] = None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] == "sphinx-skel":
        sp = _build_sphinx_parser()
        ns = sp.parse_args(argv[1:])
        out = _write_sphinx_skel(Path(ns.dest), force=ns.force)
        print(out)
        return

    ap = _build_run_parser()
    args = ap.parse_args(argv)
    cfg = ConverterConfig(
        num=args.num, den=args.den, A=args.A, B=args.B, C=args.C, D=args.D,
        iu=args.iu, tfinal=args.tfinal, dt=args.dt, sympy=args.sympy, no_plot=args.no_plot,
        save_json=args.save_json
    )
    app = ConverterApp(level=_level(args.verbose))
    res = app.run(cfg)
    if res.pretty_tf:
        print("\n== Converter Summary ==")
        print(res.pretty_tf)
    if res.pretty_sympy:
        print("\nSymPy rational form:")
        print(res.pretty_sympy)

if __name__ == "__main__":
    main()
