from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Optional

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_analysis/stateTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_analysis.stateTool.apis import RunOptions, AnalyzerMode
    from state_space_analysis.stateTool.app import StateToolApp
else:
    from .apis import RunOptions, AnalyzerMode
    from .app import StateToolApp


_PACKAGE = "state_space_analysis.stateTool"
_PROJECT = "modernControl - state_space_analysis.stateTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_analysis.stateTool.cli",
    "state_space_analysis.stateTool.apis",
    "state_space_analysis.stateTool.app",
]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it already exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> stateTool -> state_space_analysis -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the project-standard minimal Sphinx Makefile."""
    return '''# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
'''


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _handle_sphinx_skel(argv: list[str]) -> int | None:
    """Handle the sphinx-skel helper before the normal application parser."""
    if not argv or argv[0] != "sphinx-skel":
        return None

    parser = argparse.ArgumentParser(
        prog=f"python -m {_PACKAGE}.cli sphinx-skel",
        description="Create a deploy-safe Sphinx documentation skeleton for this package.",
    )
    parser.add_argument("dest", type=Path, help="Destination docs directory.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")
    args = parser.parse_args(argv[1:])

    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser for state-space analysis."""
    p = argparse.ArgumentParser(
        description="State-space analysis for controllability, observability, and stability."
    )
    g_in = p.add_argument_group("Inputs")
    g_in.add_argument("--A", type=str, help='State matrix, for example "0 1; 0 -2" or "[[0,1],[0,-2]]".')
    g_in.add_argument("--B", type=str, help='Input matrix, for example "0;1" or "[[0],[1]]".')
    g_in.add_argument("--C", type=str, help="Output matrix for observability and output checks.")
    g_in.add_argument("--D", type=str, help="Feedthrough matrix for output controllability.")

    g_tf = p.add_argument_group("Alternative SISO input")
    g_tf.add_argument("--tf", type=str, help='Rational expression in s, for example "(s+3)/(s^2+3*s+2)".')
    g_tf.add_argument("--num", type=str, help="Numerator as CSV or polynomial string.")
    g_tf.add_argument("--den", type=str, help="Denominator as CSV or polynomial string.")

    g_opt = p.add_argument_group("Options")
    g_opt.add_argument(
        "--mode",
        type=str,
        default="all",
        choices=[m.value for m in AnalyzerMode],
        help="Analysis mode to run.",
    )
    g_opt.add_argument("--pretty", action="store_true", help="Pretty-print matrices.")
    g_opt.add_argument("--numeric", action="store_true", help="Print numeric matrices.")
    g_opt.add_argument("--digits", type=int, default=8, help="Digits for numeric output.")
    g_opt.add_argument("--eps", type=float, default=0.0, help="Stability threshold used for marginal cases.")
    g_opt.add_argument("--export-json", type=str, help="Write a summary JSON file under the output directory.")
    g_opt.add_argument("--log", type=str, default="INFO", help="Logging level.")
    return p


def main(argv: Optional[list[str]] = None) -> int:
    """Run the stateTool command line interface."""
    argv = list(sys.argv[1:] if argv is None else argv)

    skel_status = _handle_sphinx_skel(argv)
    if skel_status is not None:
        return skel_status

    p = build_parser()
    args = p.parse_args(argv)
    logging.basicConfig(
        level=getattr(logging, args.log.upper(), logging.INFO),
        format="%(levelname)s: %(message)s",
    )

    app = StateToolApp()

    options = RunOptions(
        mode=AnalyzerMode(args.mode),
        pretty=args.pretty,
        numeric=args.numeric,
        digits=args.digits,
        eps=args.eps,
        export_json=(args.export_json if args.export_json else None),
    )

    if args.A and args.B:
        res = app.run_from_state(A=args.A, B=args.B, C=args.C, D=args.D, options=options)
    else:
        if not (args.tf or (args.num and args.den)):
            p.error("Provide (--A and --B), --tf, or --num and --den.")
            return 2
        res = app.run_from_tf(tf=args.tf, num=args.num, den=args.den, options=options)

    import json

    print(json.dumps(res, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
