# -*- coding: utf-8 -*-
"""Command line interface for state-space controller design."""
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

# ---------- Import shim so `python cli.py` works with absolute imports ----------
if __package__ in (None, ""):
    # Running as a script from inside state_space_design/controllerTool.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)

    from state_space_design.controllerTool.apis import RunRequest, run
    from state_space_design.controllerTool.io import PlotConfig, PlotService
else:
    from .apis import RunRequest, run
    from .io import PlotConfig, PlotService


_PACKAGE = "state_space_design.controllerTool"
_PROJECT = "modernControl - state_space_design.controllerTool"
_AUTHOR = "modernControl"
_MODULES = [
    "state_space_design.controllerTool.cli",
    "state_space_design.controllerTool.apis",
    "state_space_design.controllerTool.io",
]


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless the file exists and force is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> controllerTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with safe heading formatting."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using only known package modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _MODULES:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _normalize_negative_list_args(argv: list[str] | None) -> list[str] | None:
    """Normalize negative pole-list values so argparse does not read them as options."""
    if argv is None:
        return None

    out: list[str] = []
    i = 0
    sensitive = {"--K_poles", "--obs_poles"}
    while i < len(argv):
        tok = argv[i]
        if tok in sensitive and i + 1 < len(argv):
            nxt = argv[i + 1]
            if nxt.startswith("-") and not nxt.startswith("--="):
                out.append(f"{tok}={nxt}")
                i += 2
                continue
        out.append(tok)
        i += 1
    return out


def _build_run_parser() -> argparse.ArgumentParser:
    """Build the controller-design argument parser."""
    parser = argparse.ArgumentParser(
        prog="state_space_design.controllerTool",
        description="State-space controller design with observer support for SISO systems.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    parser.add_argument("--num", required=True, help='Plant numerator, for example "1" or "10 20".')
    parser.add_argument("--den", required=True, help='Plant denominator, for example "1 0 1 0" or "1 10 24 0".')
    parser.add_argument("--K_poles", default=None, help='Controller poles, for example "-1+1j,-1-1j,-8".')
    parser.add_argument("--obs_poles", default=None, help='Observer poles, for example "-4,-4".')

    parser.add_argument("--ts", type=float, default=None, help="Settling-time target in seconds for automatic pole selection.")
    parser.add_argument("--undershoot", default=None, help='Undershoot range as "low,high", for example "0.25,0.35".')
    parser.add_argument("--obs_speed_factor", type=float, default=5.0, help="Observer speed relative to controller pole speed.")

    parser.add_argument("--cfg", choices=["cfg1", "cfg2", "both"], default="both")
    parser.add_argument("--plots", choices=["none", "mpl", "plotly", "both"], default="both")
    parser.add_argument("--save_prefix", default=None)
    parser.add_argument("--ply_width", type=int, default=0)
    parser.add_argument("--verbose", action="store_true")
    return parser


def _run_controller(argv: list[str] | None = None) -> int:
    """Run the controller-design workflow."""
    argv = _normalize_negative_list_args(list(argv) if argv is not None else sys.argv[1:])
    parser = _build_run_parser()
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=(logging.DEBUG if args.verbose else logging.INFO),
        format="INFO: %(message)s",
    )

    undershoot = None
    if args.undershoot:
        parts = [float(x) for x in args.undershoot.replace(",", " ").split()]
        if len(parts) != 2:
            parser.error("--undershoot must contain two numbers: low,high")
        undershoot = (parts[0], parts[1])

    request = RunRequest(
        num=args.num,
        den=args.den,
        K_poles=args.K_poles,
        obs_poles=args.obs_poles,
        cfg=args.cfg,
        ts=args.ts,
        undershoot=undershoot,
        obs_speed_factor=args.obs_speed_factor,
    )
    response = run(request)

    print("\n== Build Summary ==")
    print("K:", response.result.K)
    print("Ke:\n", response.result.Ke)
    num_gc = response.result.Gc.num[0][0]
    den_gc = response.result.Gc.den[0][0]
    print("Gc num:", num_gc)
    print("Gc den:", den_gc)

    if args.plots != "none":
        systems = []
        if response.result.T1 is not None:
            systems.append(("Config 1", response.result.T1))
        if response.result.T2 is not None:
            systems.append(("Config 2", response.result.T2))
        PlotService(
            PlotConfig(
                plots=args.plots,
                save_prefix=args.save_prefix,
                ply_width=args.ply_width,
            )
        ).plot_closed_loop_bode_and_step(systems)

    return 0


def _run_sphinx_skel(dest: Path, *, force: bool = False) -> int:
    """Generate the Sphinx skeleton files for this package."""
    written = _write_sphinx_skeleton(dest, force=force)
    print(f"Sphinx skeleton ready: {dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {dest / '_static' / '.gitkeep'}")
    print(f"  {dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the controllerTool command line interface."""
    raw_argv = list(sys.argv[1:] if argv is None else argv)

    if raw_argv and raw_argv[0] == "sphinx-skel":
        skel_parser = argparse.ArgumentParser(
            prog="state_space_design.controllerTool sphinx-skel",
            description="Create a deploy-safe Sphinx documentation skeleton for this package.",
        )
        skel_parser.add_argument("dest", type=Path, help="Destination docs directory.")
        skel_parser.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")
        args = skel_parser.parse_args(raw_argv[1:])
        return _run_sphinx_skel(args.dest, force=args.force)

    return _run_controller(raw_argv)


if __name__ == "__main__":
    raise SystemExit(main())
