# -*- coding: utf-8 -*-
"""Command line interface for observerGainMatrixTool."""
from __future__ import annotations

import argparse
import importlib.util
import json
import logging
import os
import sys
from pathlib import Path

# --- Import shim so `python cli.py` works with relative imports ---
if __package__ in (None, ""):
    # Running as a script: add project root to sys.path and import absolute modules.
    pkg_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if pkg_root not in sys.path:
        sys.path.insert(0, pkg_root)
    from state_space_design.observerGainMatrixTool.apis import ObserverRequest
    from state_space_design.observerGainMatrixTool.app import ObserverGainMatrixApp
    from state_space_design.observerGainMatrixTool.utils import CSV_CPLX_RE
else:
    # Normal package execution.
    from .apis import ObserverRequest
    from .app import ObserverGainMatrixApp
    from .utils import CSV_CPLX_RE


_PACKAGE = "state_space_design.observerGainMatrixTool"
_PROJECT = "modernControl - state_space_design.observerGainMatrixTool"
_AUTHOR = "modernControl"
_REQUIRED_MODULES = [
    "state_space_design.observerGainMatrixTool.cli",
    "state_space_design.observerGainMatrixTool.apis",
    "state_space_design.observerGainMatrixTool.app",
    "state_space_design.observerGainMatrixTool.utils",
]
_OPTIONAL_MODULES = [
    "state_space_design.observerGainMatrixTool.core",
    "state_space_design.observerGainMatrixTool.io",
    "state_space_design.observerGainMatrixTool.design",
    "state_space_design.observerGainMatrixTool.plotting",
]


# ------------------------------
# Sphinx skeleton helpers
# ------------------------------

def _module_exists(module_name: str) -> bool:
    """Return true when a module can be found without importing it."""
    try:
        return importlib.util.find_spec(module_name) is not None
    except (ImportError, ModuleNotFoundError, ValueError):
        return False


def _documented_modules() -> list[str]:
    """Return the modules that should be included in generated API docs."""
    modules = list(_REQUIRED_MODULES)
    modules.extend(mod for mod in _OPTIONAL_MODULES if _module_exists(mod))
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a safe underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write text to a file unless it exists and force is false."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories with gitkeep files for Git tracking."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx configuration file."""
    return f'''# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> observerGainMatrixTool -> state_space_design -> repository root
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True
'''


def _build_index_rst() -> str:
    """Build the Sphinx index page with correct heading underline length."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
    )


def _build_api_rst() -> str:
    """Build the API page using safe, simple reStructuredText."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    for mod in _documented_modules():
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")
    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


# ------------------------------
# Helpers for robust CLI parsing
# ------------------------------

def _normalize_negative_list_args(argv: list[str] | None) -> list[str] | None:
    """Normalize selected option values that begin with a minus sign."""
    if argv is None:
        return None
    out: list[str] = []
    i = 0
    sensitive = {"--K_poles"}
    while i < len(argv):
        tok = argv[i]
        if tok in sensitive and i + 1 < len(argv):
            nxt = argv[i + 1]
            if nxt.startswith("-") and not nxt.startswith("--"):
                out.append(f"{tok}={nxt}")
                i += 2
                continue
        out.append(tok)
        i += 1
    return out


def _parser_epilog() -> str:
    return (
        "Tips:\n"
        "  - If a value starts with '-', prefer equals form, for example --K_poles=\"-3,-4\".\n"
        "  - Run as a module from the repository root or as a script in this folder.\n"
        "  - Export JSON paths with directories are written to those paths.\n"
        "  - Bare export JSON filenames are written to the current working directory.\n"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="state_space_design.observerGainMatrixTool",
        description=(
            "Observer Gain Matrix Tool for full-order observer synthesis, optional "
            "controller gain synthesis, transfer-function reporting, and zero-input simulation."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
        epilog=_parser_epilog(),
    )
    sub = parser.add_subparsers(dest="cmd")

    run_parser = sub.add_parser(
        "run",
        help="run observer gain synthesis",
        description="Run full-order observer gain synthesis and optional closed-loop calculations.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_run_arguments(run_parser)

    skel_parser = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
    )
    skel_parser.add_argument("dest", type=Path, help="Destination docs directory.")
    skel_parser.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    return parser


def _add_run_arguments(parser: argparse.ArgumentParser) -> None:
    # Plant.
    parser.add_argument("--A", required=True, help='State matrix, for example "0 1; -2 -3".')
    parser.add_argument("--B", default=None, help='Input matrix needed for controller or closed-loop calculations.')
    parser.add_argument("--C", required=True, help='Output matrix, for example "1 0" or "1 0; 0 1".')

    # Observer.
    parser.add_argument(
        "--poles",
        nargs="+",
        type=complex,
        required=True,
        help="Observer poles. Examples: -8 -8, -10 -12, or -1.8+2.4j -1.8-2.4j.",
    )
    parser.add_argument("--method", choices=["auto", "place", "ack"], default="auto")
    parser.add_argument(
        "--place_fallback",
        choices=["none", "ack", "jitter"],
        default="none",
        help="Fallback strategy when place cannot handle requested multiplicities.",
    )
    parser.add_argument("--jitter_eps", type=float, default=1e-6, help="Jitter used when fallback is jitter.")

    # Controller.
    parser.add_argument("--K", type=str, default=None, help='Explicit K row, for example "29.6 3.6".')
    parser.add_argument(
        "--K_poles",
        default=None,
        help='Controller poles as one quoted CSV string. Equals form is recommended.',
    )
    parser.add_argument(
        "--K_poles_list",
        nargs="+",
        default=None,
        help="Controller poles as separate tokens.",
    )

    # Simulation and exports.
    parser.add_argument(
        "--compute_closed_loop",
        action="store_true",
        help="Build the closed-loop augmented model, controller transfer function, and optional zero-input simulation.",
    )
    parser.add_argument("--x0", type=str, default=None, help='Initial state, for example "1,0".')
    parser.add_argument("--e0", type=str, default=None, help='Initial observer error, for example "0,0".')
    parser.add_argument("--t_final", type=float, default=0.0, help="Final time for zero-input simulation.")
    parser.add_argument("--dt", type=float, default=0.01, help="Integration step for zero-input simulation.")
    parser.add_argument("--pretty", action="store_true", help="Print a human-friendly summary instead of JSON.")
    parser.add_argument("--equations", action="store_true", help="Reserved for future pretty output expansions.")
    parser.add_argument("--eq_style", choices=["auto", "ascii", "numpy", "both"], default="auto")
    parser.add_argument("--latex", default=None, help="Write a LaTeX observer equation snippet to this filename under out.")
    parser.add_argument("--export_json", default=None, help="Write JSON to this filename.")
    parser.add_argument("--log", default="WARNING", help="Logging level.")


def _build_request(args: argparse.Namespace) -> ObserverRequest:
    return ObserverRequest(
        A=args.A,
        C=args.C,
        poles=args.poles,
        method=args.method,
        place_fallback=args.place_fallback,
        jitter_eps=args.jitter_eps,
        B=args.B,
        K=args.K,
        K_poles_csv=args.K_poles,
        K_poles_list=args.K_poles_list,
        compute_closed_loop=args.compute_closed_loop,
        x0=args.x0,
        e0=args.e0,
        t_final=args.t_final,
        dt=args.dt,
        pretty=args.pretty,
        equations=args.equations,
        eq_style=args.eq_style,
        latex_out=(args.latex if args.latex else None),
    )


def _write_export_json(export_json: str | None, data: dict) -> None:
    if not export_json:
        return
    export_path = Path(export_json)
    path_has_sep = (os.sep in export_json) or (os.altsep is not None and os.altsep in export_json)
    if export_path.is_absolute() or path_has_sep:
        export_path = (Path.cwd() / export_path) if not export_path.is_absolute() else export_path
    else:
        export_path = Path.cwd() / export_json
    export_path.parent.mkdir(parents=True, exist_ok=True)
    export_path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _run_observer(args: argparse.Namespace, unknown: list[str]) -> int:
    logging.basicConfig(
        level=getattr(logging, str(args.log).upper(), logging.WARNING),
        format="%(levelname)s: %(message)s",
    )

    # If K poles were omitted but a CSV-looking token survived parsing, capture it.
    if args.K_poles is None and not args.K and not args.K_poles_list:
        for tok in unknown:
            if CSV_CPLX_RE.match(tok):
                args.K_poles = tok
                break

    app = ObserverGainMatrixApp()
    try:
        resp = app.run(_build_request(args))
    except Exception as exc:
        logging.error(str(exc))
        return 2

    _write_export_json(args.export_json, resp.data)

    if args.pretty and resp.pretty_blocks:
        print("\n".join(resp.pretty_blocks))
    else:
        print(json.dumps(resp.data, indent=2))
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    written = _write_sphinx_skeleton(args.dest, force=args.force)
    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")
    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = _normalize_negative_list_args(list(argv) if argv is not None else sys.argv[1:])
    parser = build_parser()

    # Preserve the historical no-subcommand usage by routing unknown leading args to run.
    if argv and argv[0] not in {"run", "sphinx-skel", "-h", "--help"}:
        argv = ["run", *argv]

    args, unknown = parser.parse_known_args(argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)
    if args.cmd == "run":
        return _run_observer(args, unknown)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
